### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Eeems** [mb1986/rm-hacks#1]
There is no license for the code provided in this repository.

**Comment by mb1986** [comment]
That is right, we are still discussing how it should be licensed. There is a possibility that we will change the contents of patches stored in the repo. I would need some help in understanding if it is fine to store those patches as they currently are...

**Comment by Eeems** [comment]
You can license the patches seperately from the rest of the code. I would recommend using the MIT license for everything but the patches, and keeping those as all rights reserved or something.

**Comment by mb1986** [comment]
I understand you, let me think about it. This is probably the way to go... I'll try to "fix it" in a couple of days.
