### ISSUE TITLE
Add more stroke sizes

### ISSUE THREAD

**Issue by ygbillet** [mb1986/rm-hacks#10]
Hi,

RM2 with ddvk offers more than 3 stroke. 

Could it be possible to add other strokes. I'm really interested in 1.5 and 8 size.

**Comment by mb1986** [comment]
I know how to do that :) Will be added in the next patch v0.0.4.

**Comment by mb1986** [comment]
Could you please verify that it works as expected?

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.4
```
