### ISSUE TITLE
Stroke sizes hack cause issues with tools switching

### ISSUE THREAD

**Issue by mb1986** [mb1986/rm-hacks#100]
### Gestures
  :x: Gesture to switch between the last two tools: swipe one finger down in the top left corner (right-handed)/right corner (left-handed).
  Observation: Possible existing bug. When "More Stroke Sizes" is disabled, gesture no longer switches.
 ### Lamy Pen 
:x: The Lamy button, in addition to erasing when pressed, toggles the last two tools when clicked
   Observation: Possible existing bug. When "More Stroke Sizes" is disabled, toggle does not always switch tools. Sometimes it takes 2-4 clicks to toggle the tool. 
:x: Lamy button double-click now triggers an undo action.
   Observation: Possible exisiting bug. When "More Stroke Sizes" is disabled, double-click does not always undo.

_Originally posted by @ard0gg in https://github.com/mb1986/rm-hacks/issues/93#issuecomment-1854963232_

**Comment by atngames** [comment]
Hi @ard0gg, The gesture bug seems fixed. Since we already have specific stylus issues open, Are okay with me closing this issue ?

**Comment by ard0gg** [comment]
Sure that is fine to me. I will test out the stylus specific ones when I get a chance.

**Comment by atngames** [comment]
😉
