### ISSUE TITLE
Hack installed but failed to set proper time and Lamy eraser

### ISSUE THREAD

**Issue by pragmatically-dev** [mb1986/rm-hacks#104]
Connecting to github.com (20.201.28.151:443)
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer

**Comment by pragmatically-dev** [comment]
i tried no-check-certificate but does not work

**Comment by Eeems** [comment]
It would be helpful to provide the following information:

- reMarkable 1 or 2?
- OS version number
- The exact command run
- Does sync work currently on your device?

**Comment by pragmatically-dev** [comment]
Device: Remarkable 2
OS: 3.8.3.1976

 

sh -c "$(wget --no-check-certificate https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)"
Connecting to raw.githubusercontent.com (185.199.108.133:443)
writing to stdout
-                    100% |*****************************************************************************************************************|  7510  0:00:00 ETA
written to stdout

 rM Hacks Installer
--------------------

Trying to download and install patch: '0.0.7'
Connecting to raw.githubusercontent.com (185.199.108.133:443)
wget: note: TLS certificate validation not implemented
writing to stdout
-                    100% |*****************************************************************************************************************|  215k  0:00:00 ETA
written to stdout
The patch '0.0.7' installed successfully (hopefully)!
Would you like to install 'ddvk/remarkable-stylus' [Y/n]? Y
Connecting to github.com (20.201.28.151:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer


Just got the hack installed but the Lamy eraser does not work

**Comment by pragmatically-dev** [comment]
and yes, not sync problems so far

**Comment by pragmatically-dev** [comment]
wget "https://github.com/ddvk/remarkable-stylus/releases/download/0.0.3/libqevdevlamyplugin.so" -O /usr/lib/plugins/generic/libqevdevlamyplugin.so
this link seems to be the problem

**Comment by pragmatically-dev** [comment]
i removed the stylus install function and ill try to do it manually

**Comment by Eeems** [comment]
> wget "https://github.com/ddvk/remarkable-stylus/releases/download/0.0.3/libqevdevlamyplugin.so" -O /usr/lib/plugins/generic/libqevdevlamyplugin.so this link seems to be the problem

Ah, this will need to be changed to the raw.githubusercontent.com version of the link for it to work.

**Comment by pragmatically-dev** [comment]
steps that i used to solve this:

downloaded the .so file on pc

use filezila to put it on the remarkable

and i wrote this:

reMarkable: ~/ mv libqevdevlamyplugin.so /usr/lib/plugins/generic/
reMarkable: ~/ mkdir -p /etc/systemd/system/xochitl.service.d
reMarkable: ~/ cat << EOF > /etc/systemd/system/xochitl.service.d/evdevlamy.conf
> [Service]
> ExecStart=
> ExecStart=/usr/bin/xochitl --system -plugin evdevlamy
> EOF
reMarkable: ~/         systemctl daemon-reload
reMarkable: ~/
