### ISSUE TITLE
Battery charging doesn't show in document level

### ISSUE THREAD

**Issue by Kelvin88** [mb1986/rm-hacks#105]
Battery icon in document level not showing device is charging. Thought it was my cable or charger until I closed current document to see that device was indeed charging. Battery icon in bottom of toolbar should indicate when device is charging.

**Comment by mb1986** [comment]
You're right. Do you think replacing the battery icon with the "spark" icon while charger connected would be sufficient?

**Comment by Kelvin88** [comment]
To be consistent, maybe should use same as current lightning icon when device is charging shown in My Files page.

**Comment by mb1986** [comment]
I had exactly this lightning icon in mind.
