### ISSUE TITLE
Feature Request: replace toolbar gesture for favorite 

### ISSUE THREAD

**Issue by Kelvin88** [mb1986/rm-hacks#106]
Most of us have a favorite gesture we invoke all the time. Is it possible to have swipe down 1 finger currently used to open/close toolbar to use for a favorite, be it swapping tools/eraser/etcetera? Current swipe down gesture to open/close toolbar is easiest, invoke from practically anywhere and most accurate, pity to use it to only open/close toolbar. Or introduce swipe up, opposite to swipe down for toolbar, to assign a favorite. Thank you.

**Comment by mb1986** [comment]
I am still considering adding a feature that allows everyone to assign actions to gestures. I can't specify a timeline yet, but it is definitely on our development roadmap.

**Comment by Kelvin88** [comment]
Thank you for considering.

I find some of the current gestures a hit & miss, but I've always successfully open/close toolbar because that gesture is easy to access and very accurate. Pity to use it just for toolbar.

**Comment by Jayy001** [comment]
Falls under #60
