### ISSUE TITLE
Wrong url for ddvk/remarkable-stylus lib 

### ISSUE THREAD

**Issue by mb1986** [mb1986/rm-hacks#107]
> wget "https://github.com/ddvk/remarkable-stylus/releases/download/0.0.3/libqevdevlamyplugin.so" -O /usr/lib/plugins/generic/libqevdevlamyplugin.so this link seems to be the problem

Ah, this will need to be changed to the raw.githubusercontent.com version of the link for it to work.

_Originally posted by @Eeems in https://github.com/mb1986/rm-hacks/issues/104#issuecomment-1861911689_

**Comment by Eeems** [comment]
Since it's a release artifact, it might not be possible to use the raw URLs to access it.

**Comment by mb1986** [comment]
You may be right, I cannot see an option to download it directly. What do you think about adding a `--no-check-certificate` switch (if it is available) and verifying sha256 sum on our end?

**Comment by Eeems** [comment]
> You may be right, I cannot see an option to download it directly. What do you think about adding a `--no-check-certificate` switch (if it is available) and verifying sha256 sum on our end?

https://github.com/mb1986/rm-hacks/issues/104#issuecomment-1861856744
Apparently that didn't work.

You could try what toltec does and download a copy of wget that can handle downloading those URLs. The latest version was updated to work for 3.6, which should mean that 3.8 works: https://github.com/toltec-dev/bootstrap/

**Comment by hmenzagh** [comment]
>You could try what toltec does and download a copy of wget that can handle TLS. 

Worked for me !
