### ISSUE TITLE
Feature request: Notebook New Page - added automatically

### ISSUE THREAD

**Issue by begtognen** [mb1986/rm-hacks#108]
It would be amazing to have a new page added when I swipe the last page of the notebook, instead of also hitting the new page button.

**Comment by PepikVaio** [comment]
That's going to be a lot of blank pages again :)

**Comment by mb1986** [comment]
It will be configurable :)

**Comment by PepikVaio** [comment]
I hope so :)

**Comment by atngames** [comment]
This might happen soon 😉

**Comment by mb1986** [comment]
Yeap, thanks to @atngames who have just implemented that! (ready to be delivered in v0.0.9)

**Comment by mb1986** [comment]
It ready for testing:

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.3
```

**Comment by PepikVaio** [comment]
Works very well.

**Comment by Kelvin88** [comment]
Double tapping to remove and add page works and really nice feature.
