### ISSUE TITLE
Suggestion - global location for Lamy plugin

### ISSUE THREAD

**Issue by UniqueName992** [mb1986/rm-hacks#110]
Hey,

I notice there's an env dir which xochitl sources when launched located in `/opt/etc/xochitl.env.d/`
I've found that adding in a `lamy.env` file in this direcory, means that it's loaded even with launchers which don't respect the systemctl settings.
```bash
cat /opt/etc/xochitl.env.d/lamy.env 

export QT_QPA_GENERIC_PLUGINS=evdevlamy
```
I just thought I'd suggest it, in case adding the export here means less work overall for supporting launchers.

Thanks for the amazing mod!

**Comment by Eeems** [comment]
> Hey,
> 
> I notice there's an env dir which xochitl sources when launched located in `/opt/etc/xochitl.env.d/` I've found that adding in a `lamy.env` file in this direcory, means that it's loaded even with launchers which don't respect the systemctl settings.
> 
> ```shell
> cat /opt/etc/xochitl.env.d/lamy.env 
> 
> export QT_QPA_GENERIC_PLUGINS=evdevlamy
> ```
> 
> I just thought I'd suggest it, in case adding the export here means less work overall for supporting launchers.
> 
> Thanks for the amazing mod!

This is only if you have toltec installed. If you are using toltec, do not use this script to install remarkable-stylus, instead `opkg install remarkable-stylus`
