### ISSUE TITLE
Simplify timezone setup for proper time display

### ISSUE THREAD

**Issue by mb1986** [mb1986/rm-hacks#12]
Installation script helps (or should help at least) with setting proper timezone.

**Comment by mb1986** [comment]
Please verify if the current implementation (as of 4758acb806b89efa3ca76905714475f73f7c926a) is sufficient :)

**Comment by Eeems** [comment]
> Please verify if the current implementation (as of [4758acb](https://github.com/mb1986/rm-hacks/commit/4758acb806b89efa3ca76905714475f73f7c926a)) is sufficient :)

I already added a comment to the PR, although it looks like you merged the PR before having me review it.

**Comment by mb1986** [comment]
You're right @Eeems, sorry, I haven't thought anyone will look into it :grimacing:
I'll wait next time for feedback :)
