### ISSUE TITLE
Question - Lamy Button Toggling the writing tool - how to disable

### ISSUE THREAD

**Issue by Reguuuu** [mb1986/rm-hacks#120]
Hi guys, im kinda new to this stuff, I am on the 0.07 patch, but I do not really like that sometimes when clicking the lamy pen button the writing tool toggles, is there any way I can disable it easily. I disabled the gesture already but can't seem to disable the actual pen click function :/

**Comment by mb1986** [comment]
Hi @Reguuuu, please look at https://github.com/mb1986/rm-hacks/issues/66. I'll work on the configuration.

**Comment by Reguuuu** [comment]
Thanks a Lot :D
Dzięki Wielkie:D
