### ISSUE TITLE
Modify passcode screen

### ISSUE THREAD

**Issue by cool9333** [mb1986/rm-hacks#121]
Total noob here. I know that this is just cosmetic & may not be possible, but I would like a way to edit or modify the passcode screen - add graphics, change button styles, high contract background, etc.

**Comment by mb1986** [comment]
Should be possible.

**Comment by cool9333** [comment]
Thanks, Michał! I really appreciate all of the work you've put into this
project.



LKW

**Comment by Tridens92** [comment]
FWIW, I would be a bit nervous about playing with the passcode screen, especially for just cosmetic reasons.  Being locked out of my device because of a bug would...really suck! :)

**Comment by PepikVaio** [comment]
It's just a design :)

**Comment by Jayy001** [comment]
What specific modification would you be looking at?

**Comment by cool9333** [comment]
Wow, I forgot I made this request. Not even sure what I was thinking. You
can close it if no one else has any input.
