### ISSUE TITLE
Enhancement: Back and forward between two pages

### ISSUE THREAD

**Issue by digital-tinta** [mb1986/rm-hacks#122]
Feature request

Replicate the back and forward buttons avaliable in ddvk's to move between the last two seen/used pages.

This feature is rather convenient in situations where one is working in a particular page, but needs to check a reference/solution in another page. After consulting the reference page, hitting the back button moves back to the initial page (and, afterward, hitting the forward button moves to the reference page).

Many thanks!

**Comment by PepikVaio** [comment]
The request has already been submitted.
https://github.com/mb1986/rm-hacks/issues/26
