### ISSUE TITLE
Just thanks

### ISSUE THREAD

**Issue by anbzerc** [mb1986/rm-hacks#124]
Hi, I installed the rm racks ten minutes ago and I'm very surprised and enthusiastic about your hack, which is very, very cool, so thank you very much for your work!

**Comment by mb1986** [comment]
Hi, thanks for your kind words!

**Comment by Kelvin88** [comment]
+1. Thank you to team for making this Hack a pleasure to use. Wishing all in this community a Happy New Year 🍾
