### ISSUE TITLE
Button to jump directly to tags page (and a big thanks for the wonderful hacks)

### ISSUE THREAD

**Issue by fcr** [mb1986/rm-hacks#129]
The bookmarks are essential for quickly navigating pages within the same document.
If there was a button for jumping directly to the tags page this will make navigating pages across documents.
The button could be in a menu or the tool bar or even in the "View All" in the tags popup.

**Comment by PepikVaio** [comment]
Very good idea.

At first I thought it already had a reMarkable button.
But it's still within the same document.

**Comment by mb1986** [comment]
Do you mean `Menu/Tags` view? For example by long clicking tags toolbar button?

**Comment by fcr** [comment]
> Do you mean `Menu/Tags` view? For example by long clicking tags toolbar button?

Yes the Menu/Tags view. A long press sounds like a great solution.

**Comment by PepikVaio** [comment]
I thing so.

**Comment by rudy0ne** [comment]
If you filter the tags page by selecting TagA and TagB and then open one of the shown documents, when you exit the document back to the tags page your TagA/TagB filter is no longer selected. Can we instead retain that selection? This would avoid having to reapply the same filter over and over again when reviewing lots of documents sharing the same tags.

**Comment by mb1986** [comment]
I've just done that but it may cause issue when one untags the last page tagged by this particular tag and the tags view has been already filtered by the same tag. In other words, the list list is filtered by the non-existent tag.

**Comment by mb1986** [comment]
Ok, done, it resets when we try to filter by non-existent tag.

**Comment by rudy0ne** [comment]
Amazing! Thank you!

**Comment by fcr** [comment]
> Amazing! Thank you!

I concur. Thank you

**Comment by PepikVaio** [comment]
> Myslíš `Menu/Tags`pohled? Například dlouhým kliknutím na tlačítko panelu nástrojů tagy?

OK - same requirement #72

**Comment by PepikVaio** [comment]
> Pokud filtrujete stránku značek výběrem TagA a TagB a poté otevřete jeden ze zobrazených dokumentů, když opustíte dokument zpět na stránku značek, váš filtr TagA/TagB již nebude vybrán. Můžeme místo toho zachovat tento výběr? Vyhnete se tak nutnosti znovu a znovu používat stejný filtr při kontrole mnoha dokumentů sdílejících stejné značky.

OK - same requirement #26

**Comment by rudy0ne** [comment]
Thought I'd add this here as well, regarding alpha.2 version: 

If you close a document the normal way (one-finger swipe down) perhaps it should always return you to that document’s directory instead of the tags view, since we can already just long-press the tags button for that. What do you think?

**Comment by fcr** [comment]
> Thought I'd share this here as well, regarding alpha.2 version:
> 
> If you close a document the normal way (one-finger swipe down) perhaps it should always return you to that document’s directory -- like it did prior to the hacks -- instead of the tags view, since we can already just long-press the tags button for that. What do you think?

That would add an extra step to my workflow where I jump between tags: currently jump to tag, do something, swipe down, jump to tag. This new suggestion would make this: jump to tag, do something, open the side toolbar, long press the tag button, jump to tag, close side tool bar.

**Comment by PepikVaio** [comment]
I agree with @fcr

**Comment by rudy0ne** [comment]
Or perhaps a new button somewhere in the tags view page, which will remove the applied tags filter and take you back to the last open directory 🤔

**Comment by PepikVaio** [comment]
To would be great.

**Comment by mb1986** [comment]
This one is ready for testing:

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.3
```

> Or perhaps a new button somewhere in the tags view page, which will remove the applied tags filter and take you back to the last open directory 🤔

Please raise the separate issue for that.
