### ISSUE TITLE
Add additional gestures

### ISSUE THREAD

**Issue by Gaibhne** [mb1986/rm-hacks#13]
I saw a few issues for specific gestures already exist (#8, #9), but I thought it would be a good idea to have one issue tracking status/progress of all the various gestures that ddvk's hacks added/offered and other gestures people might come up with.

### General
- [x] Undo/redo (top center one finger left/right in ddvk)
- [ ] Zoom to specific predefined levels (was present in an old version of either rM software or ddvk) like 150%, 200%, 400%

### Tools
- [x] Switch between two most recent tools (top left one finger down in ddvk, tracked in #9)
- [x] Toggle eraser (top left one finger up in ddvk)
- [x] Toggle toolbar (center one finger down in ddvk, tracked in #8)
- [x] Switch between two most recent colors (top rightone finger up in ddvk)
- [x] Change pen thickness (top right one finger down in ddvk)

### Document
- [x] Exit document (top center one finger down in ddvk)
- [x] Switch between two most recent documents (center two fingers down in ddvk)
- [x] Toggle 'recent documents' view (center two fingers up in ddvk)

**Comment by mb1986** [comment]
Thanks @Gaibhne, it will be easier to track it here :)

I think some of those are already there in native rM:

- Exit document (top center one finger down in ddvk) - this one is in native implemenataion.
- Undo/redo (top center one finger left/right in ddvk) - two finger tap, three finger tap do the job.
- Toggle 'recent documents' view (center two fingers up in ddvk) - two finger swap from the top.

Do you agree that we will not focus on the above ones?

**Comment by Gaibhne** [comment]
> I think some of those are already there in native rM:
> 
>     * Exit document (top center one finger down in ddvk) - this one is in native implemenataion.
>     * Undo/redo (top center one finger left/right in ddvk) - two finger tap, three finger tap do the job.
>     * Toggle 'recent documents' view (center two fingers up in ddvk) - two finger swap from the top.
> 
> Do you agree that we will not focus on the above ones?

That makes sense, I'll mark them as done unless someone with a stock rM/rM2 objects - I am on 2.5 with ddvk and currently don't dare to attempt stock and hope I can revert, and until gestures, strokes and reading mode/zen mode are supported for 3.x I'm not switching, so I can't test your comments myself.

**Comment by mb1986** [comment]
I think those two may be also checked:

- Switch between two most recent tools (top left one finger down in ddvk, tracked in https://github.com/mb1986/rm-hacks/issues/9)
- Toggle eraser (top left one finger up in ddvk)

**Comment by ZacharieALES** [comment]
Do these two features seem doable?
- Switch between two most recent colors (top rightone finger up in ddvk)
- Change pen thickness (top right one finger down in ddvk)

I was using them constantly and I would be very grateful if it was possible!

**Comment by mb1986** [comment]
What gesture would you suggest to use to "Switch between two most recent documents (center two fingers down in ddvk)"? Two fingers up and down are occupied by page scroll/grow functionalities.

Do you think two-finger up swipe from the bottom of the page would be convenient? Similarly to two-finger down swipe from the top to open recent documents drawer.

**Comment by PepikVaio** [comment]
How many fingers can be used? :) Ideally with a down gesture.
3 fingers?

**Comment by mb1986** [comment]
> Do these two features seem doable?
> 
> * Switch between two most recent colors (top rightone finger up in ddvk)
> * Change pen thickness (top right one finger down in ddvk)
> 
> I was using them constantly and I would be very grateful if it was possible!

I'd like to confirm only:

- Switching between two most recent colors only, and not cycle through all the colors?
- Cycle through all the pen thicknesses?

**Comment by mb1986** [comment]
> How many fingers can be used? :) Ideally with a down gesture. 3 fingers?

Three fingers does not work properly for swipe, I've tested it and it is recognized once per 10 swipes :(

**Comment by PepikVaio** [comment]
Then 1 finger up.
There is probably no other option.

**Comment by mb1986** [comment]
One finger up and down are also used for scrolling/growing.

**Comment by PepikVaio** [comment]
When the Gesture to toggle toolbar function is activated, one finger up doesn't do anything.

**Comment by mb1986** [comment]
That is right but in #37 it has been pointed out that:

> ... the scrolling gesture with two fingers works significantly worse with the hacks installed ...

And you don't like the finger swipe from the bottom, do you? ;)
Don't you think one finger up would be to easy to switch documents? One may switch documents accidentally.

**Comment by PepikVaio** [comment]
You're right, that's why I have disabled the gesture for closing the menu, after that scrolling works just fine.

You're right, one finger can randomly switch documents.
So try from below - if it works well in the test.

**Comment by mb1986** [comment]
I think I'd stick to that for now. I'd be very happy to hear/read your feedback when it is released.

In the future I plan to make it even more configurable, that everyone would be able to choose which gesture should trigger which action.

**Comment by PepikVaio** [comment]
Split screen would be the best :)

**Comment by Kelvin88** [comment]
My 2 cents even though I rarely change pen thickness, should stick to recent 2 pen thickness instead of cycle through to be consistent with tool + colour. In users mind, it is recent 2 for all toggling.

**Comment by Gaibhne** [comment]
I have not seen mentioned double click (in a specific area and/or with multiple fingers); is 'double click' something that could be supported, or does the hardware/base OS not support that ?

**Comment by mb1986** [comment]
It should be double with only one drawback - when you have actions for single and double click/tap then the action for the single one will be delayed due to waiting for the second click/tap. Apart from that I think it may work.

**Comment by Gaibhne** [comment]
I was thinking maybe the predefined zooms could be realized by doing consecutive double clicks in the documents center - first double click does 125%, second double click 150%, 200%, 400% and back to 100% ? Alternatively maybe double click at top goes to 100%, double click at the bottom 400% and spread the rest in the middle ?

**Comment by PepikVaio** [comment]
Good idea. 

I'd like to return the zoom map.
As it was in the earlier version of rm.
It was nice to see where I was on the page. And I could click into the minimap and be taken to the site right away.

**Comment by DutchJoe** [comment]
> My 2 cents even though I rarely change pen thickness, should stick to recent 2 pen thickness instead of cycle through to be consistent with tool + colour. In users mind, it is recent 2 for all toggling.

The ddvk hack's to cycle thru pen thickness and pen color (one finger top right up/down) are one of the most frequently used gestures I use. Though in all fairness, in almost cases, it is just toggling between two our of the three. So toggling would be perfect!

**Comment by rudy0ne** [comment]
Please add Favorites as an option for the two-finger swipe up from the bottom gesture.

**Comment by mb1986** [comment]
> Please add Favorites as an option for the two-finger swipe up from the bottom gesture.

Favorites are accessible by two-finger swipe down from the top of the page natively (there are Recent and Favorites tabs).

**Comment by rudy0ne** [comment]
Oh I know. I just find that swiping up from the bottom, whether in portrait or horizontal, is much more practical than swiping down from the top edge given that there's a bigger bezel at the bottom to give your fingers a starting point. At least that has been my experience. 

But I see that cycling of two recent documents is up next which will be very useful, so thank you so much!

**Comment by mb1986** [comment]
In v0.0.6 a couple of gestures has been added (I've checked the marks in the first comment). I will be working on the zoom one in the separate issue https://github.com/mb1986/rm-hacks/issues/53.

**Comment by Kelvin88** [comment]
@mb1986 thank you for all the work you & team put in. Very impressed with speed of features implementation. Extending top left corner for eraser selection + pen toggle on 0.0.6 helps a bit but still struggle to consistently toggle them. Using Marker without eraser relies a lot on swapping eraser + pen, hopefully we can soon have option to change swiping up or down (now default for toolbar toggle) middle of screen for erase selection + pen as per #36. Middle of screen is much easier to access + gesture consistently works there. Pity to have it just for toolbar. Thank you.

**Comment by PepikVaio** [comment]
Hey, I noticed an interesting thing.

When I get to the reMarkable menu and want to do a gesture from the bottom to get to the previous document - nothing is done.

Could this be implemented?

**Comment by atngames** [comment]
Hi, it seems that everything here has been implemented.
Only the zoom one is left.

Rm had greatly improved their zoom gesture, is there still a need for it?

**Comment by PepikVaio** [comment]
I would especially like the zoom minimap from the official version.

**Comment by atngames** [comment]
What is that?

**Comment by PepikVaio** [comment]
Well, I had to go back to 1.9.0.0 😀

**Comment by atngames** [comment]
I don't remember 🤔🤗

**Comment by PepikVaio** [comment]
This is video:

https://1drv.ms/v/s!AhI1pC-JHcQPg_5zOGtJ6hb15wynoQ?e=XV7tyv

**Comment by hakunamatatarr** [comment]
Uh seeing that I like especially the zoom selection feature! Could be either like it was implemented back then or automatically drawing a box with the right aspect ratio. But as far as I understood, the selection tool is not so easily accessible to you, no?

**Comment by knox-dawson** [comment]
I myself would like to NOT have the "mini map" part, but back in the day, I used zoom selection ALL THE TIME.

**Comment by Jayy001** [comment]
Closing this as most of the items have been completed and we can have a separate issue for zooming to pre-defined levels.
