### ISSUE TITLE
Thank you so much for your work

### ISSUE THREAD

**Issue by pragmatically-dev** [mb1986/rm-hacks#130]
This is not an issue but I'm not able to contain myself, your work is incredibly amazing, it has improved my productivity a LOT, thank you so much.

Pd: Would you consider to pin an USDT (Tether) address to support the project?

**Comment by mb1986** [comment]
Thank you for the kind words; it is really nice to read them. I am happy that what I/we do may make someone's life easier :) I do not consider any other support needed than your feedback and new issues to work on ;) Thanks and have a good one!

**Comment by PepikVaio** [comment]
That's what I call passion for a cause :)
Seeing how the problems (requirements) are expanding, I think it must be getting annoying :)

**Comment by rudy0ne** [comment]
> Thank you for the kind words; it is really nice to read them. I am happy that what I/we do may make someone's life easier :) I do not consider any other support needed than your feedback and new issues to work on ;) Thanks and have a good one!

There at least should be an eink award every year, and you've got my vote 🙌

**Comment by pragmatically-dev** [comment]
Each upgrade is like Christmas haha my hype for the 0.0.9 goes beyond the clouds
