### ISSUE TITLE
Small fix: Bookmark tap area when disabled still not writable

### ISSUE THREAD

**Issue by al-n** [mb1986/rm-hacks#132]
It seems that with the new feature for bookmarks in v0.0.8 there is the following issue:
1. Disable the "Tap in corner opposite of toolbar to set bookmark" feature in settings
2. Then the area where this bookmark tap would happen is still not writable in documents

Do you think this is something that could be addressed?

Thanks and thanks so much in general for those wonderful hacks!!

**Comment by mb1986** [comment]
Sure, I think it is already addressed and waiting for v0.0.9 to be released in a couple of days :)
Please re-verify it when there will be a PR for v0.0.9.

Thanks for the feedback!

**Comment by al-n** [comment]
Amazing!

**Comment by mb1986** [comment]
Could you please verify if it is fixed in _alpha.2_ version?

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.2
```

**Comment by PepikVaio** [comment]
Problem solved :)

**Comment by al-n** [comment]
Works like a charm, thanks :)
