### ISSUE TITLE
the missing docs (screenshots)

### ISSUE THREAD

**Issue by RedTartan04** [mb1986/rm-hacks#141]
I couldn't resist installing your great hacks :-)
What I would have liked previously were some screenshots of how it would look like. I coudn't find any. So here are some, covering most if not all features of 0.0.8.

(note I have set Font Size to Large, which also makes thumbnails larger)

![10 share options](https://github.com/mb1986/rm-hacks/assets/99086095/4831caef-0f4a-4bce-ab02-8dba29fcbed0)

![00 settings](https://github.com/mb1986/rm-hacks/assets/99086095/2c4c359a-9c1f-4f29-977a-2c0f8254e74c)
![00-1-1 settings general](https://github.com/mb1986/rm-hacks/assets/99086095/b1c5ada8-eb4a-4a7f-b9a0-ac6a3198b956)
![00-1-1 settings applied](https://github.com/mb1986/rm-hacks/assets/99086095/e2b02dde-7f02-4cf4-92ec-15dc3d0fc4d1)
![00-2 settings gestures](https://github.com/mb1986/rm-hacks/assets/99086095/6a0156c2-4545-4cee-a987-67ef5c15a21e)
![00-2 gestures doc - sleep](https://github.com/mb1986/rm-hacks/assets/99086095/bcb2a1b6-55fc-47d2-b366-4dba655a7c55)
![00-3 settings bookmarks](https://github.com/mb1986/rm-hacks/assets/99086095/d06ec02d-5c00-4952-aec2-628b7802a60a)

![02-1 pen tools](https://github.com/mb1986/rm-hacks/assets/99086095/b80785b6-914e-41f6-8af6-915af2faf1c9)
![03 eraser tools](https://github.com/mb1986/rm-hacks/assets/99086095/71228a92-8d68-44f1-a77c-43942a925064)

![20 bookmarks toggle](https://github.com/mb1986/rm-hacks/assets/99086095/71176cda-a7b9-40da-b7af-520c571247ef)
![23 bookmark rename](https://github.com/mb1986/rm-hacks/assets/99086095/a46b0612-adbd-4baf-bb21-1a21ee12ebaa)

![31 notebooks compressed list](https://github.com/mb1986/rm-hacks/assets/99086095/4445b7c5-62fe-4f2c-a69e-5b654ebed70e)
![40 pen button](https://github.com/mb1986/rm-hacks/assets/99086095/bb97e63d-2c35-4925-8cdc-5c8523bd0a15)

**Comment by dstango** [comment]
Great, that's very helpful! Thank you!

How about providing a PR that adds these images to the README?

**Comment by ilbonte** [comment]
Similar from reddit: https://www.reddit.com/r/RemarkableTablet/comments/191tt03/rmhacks_rocks/

**Comment by knox-dawson** [comment]
I just noticed this page: https://github.com/mb1986/rm-hacks/blob/main/docs/regression-test-checklist.md
It may be a pretty good starting point for a user manual sort of doc.

**Comment by RedTartan04** [comment]
> This is really cool. Maybe for v0.1 we should have a proper doc? Could we use these for our documentation if needed?

Sure. I wont have time to edit a manual.

**Comment by mb1986** [comment]
What do you think about enabling the Wiki for the documentation in the repo?

**Comment by mb1986** [comment]
I've opened the wiki to be publicly accessible (and editable): https://github.com/mb1986/rm-hacks/wiki

**Comment by knox-dawson** [comment]
I see this wiki page: https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation

I'm interested in adding pages there, but wanted to get opinions about organization.  Just for starters, what about this sort of outline:

  - Installation
  - Settings / Configuration
  - Features Overview
  - Features Deep Dive
      - Gestures
      - Strokes
      - Bookmarks
      - Pen Button Actions
      - Document-level Settings

That is, I'm imagining a wiki page for each topic.

**Comment by atngames** [comment]
this proposal seems on point.
Probably we should wait for release 0.0.9 since there will be changes in the settings. (Or you could try the latest rmhacks alpha?)

**Comment by knox-dawson** [comment]
> Probably we should wait for release 0.0.9 since there will be changes in the settings.

I'm not opposed to adding everything for 0.0.8, and then changing as needed.  It's something (changing for new releases) that will need to happen anyway.

**Comment by chucktomasi** [comment]
What are your thoughts to make the pages version friendly. E.g. Bookmarks is available in 0.0.8 and higher?

**Comment by atngames** [comment]
You don't think we should have docs only for the latest version?

**Comment by knox-dawson** [comment]
I have a question about images in the wiki.  If I paste an image (like a screenshot), I get a link like this:

![image](https://github.com/mb1986/rm-hacks/assets/154367947/a2211c0c-7c99-47ce-b0bb-e2f031ae0ec4)

and the image gets stored outside the repo.  I'm hoping to store images in the (wiki) repo, but I have not found a way to do that.

The github docs (https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#linking-to-images-in-a-repository) show that you can store images in the (non-wiki) repo and then link to them.  But I don't think storing wiki files in the regular repo is a good idea.  But I'm not an expert here.

Otherwise, rather than editing an image file for an image in the wiki, we could just replace the image every time it needs to change.  The alt text can be descriptive even if the image name won't be.

**Comment by knox-dawson** [comment]
FWIW, this is essentially done:

https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation

I make no claims of ownership, so I hope everyone feels free to make changes and improvements.

I do plan to update what I can when version 0.0.9 is released.

Finally, I did not enter anything for Pen button actions.

https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation#pen-button-actions

I tried them out with my Lamy and some other off-brand pens with buttons.  In every case, attempting to use these features gave me a strong urge to throw the pen across the room.

So if you use those features, please have at it.

**Comment by RedTartan04** [comment]
awsome https://github.com/mb1986/rm-hacks/issues/186
