### ISSUE TITLE
Bug ? Change to the way the strokes appear on the notebook

### ISSUE THREAD

**Issue by merlebleue** [mb1986/rm-hacks#149]
Hi ! I'm using the Lamy Pen and just installed this hack.

First of all, thanks a lot to you all for the time you spent on this very usefull hack. However, I have a feeling the strokes are more precise but therefore uglier since I installed the patch...

Am I the only one with this impression ? Did you change anything to the way remarkable understands the pen strokes?

Thank you,

Julien

**Comment by mb1986** [comment]
Hi, frankly speaking I haven't noticed that. Anyone else sees the same issue?

**Comment by PepikVaio** [comment]
I hadn't noticed.
Can you provide a before and after photo?

**Comment by merlebleue** [comment]
Hi, maybe I went a bit too fast, sorry. 

I said it out of a feeling while writing, but it seems comparing what I wrote before and after installing the hack does not show any noticable difference, so maybe I just got the feeling out of nothing.

Sorry !

**Comment by PepikVaio** [comment]
OK - Can you close issue?

**Comment by merlebleue** [comment]
I have just done further testing uninstalling the hack and I can confirm the issue is from something else. I suspect my tip got a bit more used right at the moment and therefore the strokes lasted longer, which made me feel uneasy.

I'll close the issue.

**Comment by mb1986** [comment]
Thanks for the confirmation!
