### ISSUE TITLE
Script improvements: No update

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#151]
Maybe it would be a good idea, after installing the hack, to disable automatic updates?

That option is in the hack, so I think the changes would be enough just to have the settings written down.

It would be nice for people who forget to turn it off manually.

Ideally information in the terminal that automatic updates are now disabled so they don't lose hacks.

**Comment by mb1986** [comment]
You can use what @Eeems suggested, but I could also think about disabling updates on restart. No terminal information though - it is a different world.

**Comment by PepikVaio** [comment]
I mean, it's like this: If we understand each other correctly.


In your script:
# TODO - add support for different triggers
echo "Have fun, until next time, bye!"
**_echo "Auto-update is disabled!"_**
exit 0

**Comment by Eeems** [comment]
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code
