### ISSUE TITLE
Feature request: Add pen thickness and color to the brush icon when toolbar expanded

### ISSUE THREAD

**Issue by mb1986** [mb1986/rm-hacks#155]
Great point! I think it should take the place of the toolbar button somehow. Sorry for my awful photoshop skills:

![Screen Shot 2024-01-09 at 11 13 52 PM](https://github.com/mb1986/rm-hacks/assets/22302732/3de20901-f9fd-46eb-a19f-ce668be1a630)

_Originally posted by @rudy0ne in https://github.com/mb1986/rm-hacks/issues/71#issuecomment-1884164713_

**Comment by mb1986** [comment]
Your photoshop skills are good enough ;)

**Comment by atngames** [comment]
This is definitely done and working on current alphas 🎯

**Comment by rudy0ne** [comment]
> This is definitely done and working on current alphas 🎯

Wait, I haven't seen this. Unless you mean when QuickTools replaces the toolbar header. But I don't see how to view color and stroke size on the toolbar icon itself.

**Comment by atngames** [comment]
Oh sorry I thought this was for the fullscreen button.

**Comment by atngames** [comment]
This seems doable, since we already have the buttons made. We'll look into that pretty soon
