### ISSUE TITLE
Idea: Reduce the width of the tools panel (alpha.3)

### ISSUE THREAD

**Issue by pragmatically-dev** [mb1986/rm-hacks#156]
![IMG_20240111_155149](https://github.com/mb1986/rm-hacks/assets/59318726/752b37d9-5bf7-45aa-b5ce-cdb3145a90d4)

I think that it could ve great to also cut that unused width

**Comment by PepikVaio** [comment]
I also think it's to match.

**Comment by mb1986** [comment]
I agree, there are more foldouts that are similarly too wide.

**Comment by PepikVaio** [comment]
I agree.
![IMG_3250 (kopie)](https://github.com/mb1986/rm-hacks/assets/36114753/6f2ab362-6f3b-4709-9c8e-5f7b271b3980)

**Comment by RedTartan04** [comment]
Will the smaller toolbar be an option? I think I'd rather stay with the original width.

**Comment by PepikVaio** [comment]
You'll be able to choose.

**Comment by atngames** [comment]
It is going to be fixed in an upcoming alpha
