### ISSUE TITLE
Tags in the list view overlap the document names

### ISSUE THREAD

**Issue by JBlocklove** [mb1986/rm-hacks#157]
I love the "Compressed file list" setting, but documents with tags now show up with the tags overlapping their names:
![rM Screen 2024-01-11 14_17_57](https://github.com/mb1986/rm-hacks/assets/24708457/c6030a42-e78b-46d1-94c8-e7d7cc54e89d)

I opened a similar issue a while back in the ddvk hacks (https://github.com/ddvk/remarkable-hacks/issues/463) and I don't think it ever got resolved.

**Comment by mb1986** [comment]
How would you suggest solving the issue?

**Comment by PepikVaio** [comment]
I guess you can't have everything :)
Interesting, I hadn't noticed, I hardly use this view.

How to solve it?
1. Zoom in?
2. Move the tags to the right? What if the title is long?

**Comment by JBlocklove** [comment]
I think making the view just tall enough to fit the tags under the titles would be a good solution. It would still be far more compact than the original view. Or potentially reformat how tags are shown (I'm not sure what your limitations are with the project). Rather than have them in their little bubbles that take up space you could display them under the title in a format like `Tags: <tag 1>, <tag 2>, etc.` I think doing that would let you keep the sizing of the documents the same since you could use the same font size that the file size and page counts takes up.

**Comment by PepikVaio** [comment]
For me option 1 (enlarge) is the right solution but I don't use it much.

**Comment by atngames** [comment]
I went for option2 (tags at the right of the title) for now, it should be okay for most cases.

If there are lots of requests, we will go down the more complex road of option 1 (tags under the title if title + tags is too long). Not sure if this would be worth the time spent to make it...

**Comment by JBlocklove** [comment]
I just updated to 0.0.9-alpha.10 which looks to implement this and it seems to have caused a different issue. Now the author metadata is overlapping the title. Also mentioning this on the Discord.
![rM Screen 2024-01-30 20_45_18](https://github.com/mb1986/rm-hacks/assets/24708457/80d9dda3-ec48-4210-ba65-792e755e44f8)

**Comment by atngames** [comment]
Okay this will be changed in next alpha

**Comment by atngames** [comment]
This has been changed in current release, so I am closing this issue.

Feel free to open a new one for additional enhancement of compressed list
