### ISSUE TITLE
rm-hacks Guide

### ISSUE THREAD

**Issue by somedaygone** [mb1986/rm-hacks#162]
a) I would love for someone to proofread this.
b) If you like it, feel free to publish it here.

I can send you a Word document if you want it, and I'm willing to keep it up to date and add Mac instructions.
[rm-hacks Guide 0.0.8.pdf](https://github.com/mb1986/rm-hacks/files/13926804/rm-hacks.Guide.0.0.8.pdf)

**Comment by pragmatically-dev** [comment]
Amazing job @somedaygone

**Comment by RedTartan04** [comment]
Great! From scrolling through it looks ok. And thanks for linking to my screenshots :) Feel free to include any of them in your guide. I was just lazy so I dumped them in an issue ;-)

**Comment by ilbonte** [comment]
Nice work, I just want to point out this thread regarding the documentation: https://github.com/mb1986/rm-hacks/issues/141

Also, I want to add that I'm not a big fan of having it on Word, it would be a better idea to have it here on GitHub as a .md file so that everyone can contribute using pull requests...

**Comment by RedTartan04** [comment]
> Nice work, I just want to point out this thread regarding the documentation: #141
There actually is a link my sceenshots :) 

> Also, I want to add that I'm not a big fan of having it on Word, it would be a better idea to have it here on GitHub as a .md file so that everyone can contribute using pull requests...
Yeah, markdown is the more "cummunityish" way. @somedaygone it's a good idea to learn a bit of markdown; it's easy and there are various editors with previews out there.

**Comment by Eeems** [comment]
Another good thing about markdown or restructured text is that you can create a website out of it easily, and set it up so that changes to the source are automatically deployed to the site. [remarkable.guide](https://remarkable.guide/) is an example of this.

**Comment by chucktomasi** [comment]
I'm happy to help with the markdown conversion if you care to share the original Word doc. Just keep in mind that the layout is not going to look EXACTLY like the Word formatting.

**Comment by mb1986** [comment]
I've opened the wiki to be publicly accessible (and editable): https://github.com/mb1986/rm-hacks/wiki

**Comment by knox-dawson** [comment]
I missed a bit of this discussion while I was working on a PR for a "user manual".  I wonder if this should instead just be added in the wiki.

https://github.com/knox-dawson/rm-hacks/blob/20230112-knox-dawson-user-manual/docs/user-manual.md

**Comment by chucktomasi** [comment]
Nice work. Just my initial thoughts. Option 1, move the MD to a wiki page and link from the top level there. Option 2, leave the current MD page where it is and link to it from the wiki.

**Comment by knox-dawson** [comment]
Another option: I hesitated to create multiple docs, but this could be broken into multiple wiki pages.

**Comment by knox-dawson** [comment]
FWIW: https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation

**Comment by PepikVaio** [comment]
Excelent

**Comment by cool9333** [comment]
Very nice!

Thanks,
LKW

**Comment by chucktomasi** [comment]
Very nice!

**Comment by somedaygone** [comment]
I added install steps to the documentation page. If it's too long, it could be moved to a separate page. Hoping someone else can add Mac directions. Please freely edit anything there. My file with screenshots is attached too.
[rm-hacks Guide 0.0.8.docx](https://github.com/mb1986/rm-hacks/files/14074691/rm-hacks.Guide.0.0.8.docx)

**Comment by knox-dawson** [comment]
> I added install steps to the documentation page. If it's too long, it could be moved to a separate page. Hoping someone else can add Mac directions. Please freely edit anything there. My file with screenshots is attached too. [rm-hacks Guide 0.0.8.docx](https://github.com/mb1986/rm-hacks/files/14074691/rm-hacks.Guide.0.0.8.docx)

I plan to add this to the 0.0.9 docs, maybe as a separate page so it can be referenced in other pages.  But I thought I'd wait until 0.0.9 goes live.
