### ISSUE TITLE
Feature request : improve visibility of number/color letter on pen icon (when panel is not displayed)

### ISSUE THREAD

**Issue by merlebleue** [mb1986/rm-hacks#164]
Hi ! 

I'm testing on v0.0.9-alpha.5, and I'm very much enjoying the new reduced panel and the letters instead of the circle. However, if there is a note under the button, the visibility is very much decreased. I would like to have an option to add a background under it in order to increase readability of the letters as well as the number. Could be only reduced to the letter + number (white circles ?).

A shrink panel toggle in the "share" panel would also help a bit.

Thank you very much !

**Comment by merlebleue** [comment]
Here is a screenshot (using screen share, so ofc the color is gray on the tablet.

![image](https://github.com/mb1986/rm-hacks/assets/67027800/e8e5cad2-a8c2-4c49-93ae-fbfdd243fec3)

**Comment by atngames** [comment]
Completed in the current release
