### ISSUE TITLE
install patches

### ISSUE THREAD

**Issue by cool9333** [mb1986/rm-hacks#167]
If I want to install a patch to test it, is this the correct syntax to use?

sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch add quickTools version

**Comment by mb1986** [comment]
It is:

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch quickTools
```

**Comment by cool9333** [comment]
Thanks, Michal!

LKW
