### ISSUE TITLE
Ideal worflow

### ISSUE THREAD

**Issue by atngames** [mb1986/rm-hacks#169]
I have been sketching my ideal workflow (single swipes, double swipes and tapping gestures) to think how I could have it work using rmhacks and here is what I came out with:

Spoiler: At first I wanted to show my ideal thing but this might be better.

Ideally, we would have actions that we could apply to gestures. There could be
swipes in the middle of the screen,
swipe from a side, divided in three
swipe from top or bottom, divided in three
Swipe 2 fingers in the middle of the screen
Swipe 2 fingers from the top
Swipe 2 fingers from the bottom
Tapping once in the middle
Tapping twice in the middle
Tapping twice in the top
Tapping twice in the bottom
Tapping twice in the left
Tapping twice in the right

In the settings, we would have a page where we could assign actions (close document, go to next page and so on) to those gestures.
This is a big work but could be extremely rewarding since so flexible.
Let's make it a long term plan :D

**Comment by Jayy001** [comment]
Falls under #60
