### ISSUE TITLE
Still working on Version 3.8.1.1955

### ISSUE THREAD

**Issue by Am4rantheus** [mb1986/rm-hacks#17]
Hi folks, 

I just wanted to load the hack to my device but just yesterday it seems to have loaded the beta version 3.8.1.1955. Is it save to give it a try or should I wait until you also updated the hack?

**Comment by mb1986** [comment]
Hi @Am4rantheus, unfortunately, you won't be able to try it. The hacks need to be specifically prepared for a particular version, and there is a verification check in place.

I am not participating in the beta program and to prepare the hacks earlier I would need to have the binary and some cache files...

**Comment by Eeems** [comment]
https://remarkable.guide/faqs.html#why-doesn-t-toltec-support-the-beta-os-versions
You also agree not to install third party software as part of participating in the beta.

**Comment by mb1986** [comment]
I'm closing this for now because there's nothing more to be done at the moment. I'll update the hacks as soon as 3.8 is released.

**Comment by Am4rantheus** [comment]
Thanks for your information, what a pitty. Ill wait until the hack releases and look forward to it.
