### ISSUE TITLE
Lamy pen eraser switches to pen

### ISSUE THREAD

**Issue by Syycorax** [mb1986/rm-hacks#171]
When holding the button to erase, it sometimes switches back to the pen with a default (medium) pen size.

## Expected Behavior
The eraser should stay selected as long as the button is held, and switch to the previous pen size if released

## Steps to Reproduce
1. Select a pen size other than medium (I use 1.5, but other sizes might work too)
2. Hold down the button and move the pen across the screen
3. Release the button without lifting the pen (can sometimes happen without releasing the button)
4. Observe the change in size

## Version
3.9.3.1986 (rm Hacks v 0.0.8)

I will provide a screen recording as soon as possible to demonstrate the issue

**Comment by mb1986** [comment]
I've refactored the pen buttons handling and cannot reproduce it now.

**Comment by Syycorax** [comment]
I updated to the newest alpha version and there is no problem anymore.
