### ISSUE TITLE
Document clock toolbar setting in 0.0.9-alpha.6 version

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#181]
I thought I'd take a look at 0.0.9-alpha.6 version.  Pretty amazing stuff.

I noticed the description for Document clock Toolbar Setting looks incorrect.  That should be "at the top", right?

![Document clock setting](https://github.com/mb1986/rm-hacks/assets/154367947/c230ea01-e6c7-4f43-a135-393a5d237b08)

(I mentioned this in Discord, too.  Sorry for duplication.)

**Comment by atngames** [comment]
(will be fixed in upcoming alpha version

**Comment by knox-dawson** [comment]
Confirm fixed in alpha.10
