### ISSUE TITLE
Github newbie help - how do I download alphas / betas?

### ISSUE THREAD

**Issue by Tridens92** [mb1986/rm-hacks#185]
I'm sorry to have to ask, but I've dug around in the issues and documentation and can't figure this out.

How do we access current alphas / betas?

Thanks so much for help for a github newbie!

**Comment by mb1986** [comment]
When you want to test alpha build you should run the below command on you device for the latest alpha:

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.6
```

We also have a discord and there are notifications about the alpha builds: https://discord.gg/bgVXW2bchN
