### ISSUE TITLE
New 0.0.9 documentation in the wiki

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#186]
The wiki now includes tentative docs for version 0.0.9 (based on 0.0.9-alpha.6).  I expect it will change as 0.0.9 is finalized.

The docs for 0.0.8 are still there.  Github's lack of support for page hierarchy in the wiki is a bit freaky, so there's a sidebar that will hopefully make it less confusing.

Feedback and correctlions are welcome.

https://github.com/mb1986/rm-hacks/wiki

**Comment by mb1986** [comment]
I really appreciate all the work you've put and you are putting into this, thank you! :bowing_man:

**Comment by knox-dawson** [comment]
> I really appreciate all the work you've put and you are putting into this, thank you! 🙇‍♂️

Hey, what you do, I can't do. And THAT I appreciate tremendously.

**Comment by atngames** [comment]
This is super duper helpful

**Comment by Tissefantonsen** [comment]
Hi, great work!

Could we please have this documentation as part of the hack?

**Comment by atngames** [comment]
you mean on the tablet?

**Comment by Tissefantonsen** [comment]
Yes :-)

**Comment by knox-dawson** [comment]
So I cloned the wiki and ran this command:

```
pandoc --pdf-engine=xelatex -V geometry:margin=1in -o rm-hacks.pdf rM-Hacks-Documentation-0.0.8.md Settings-Configuration-0.0.8.md Features-Overview-0.0.8.md Gestures-0.0.8.md Strokes-0.0.8.md Bookmarks-0.0.8.md Document-Level-Settings-0.0.8.md
```
It came out better than I expected.

[rm-hacks.pdf](https://github.com/mb1986/rm-hacks/files/14018567/rm-hacks.pdf)

**Comment by knox-dawson** [comment]
Obsidian does a better job, though I'm still struggling with images being orphaned from their description.

[rM-Hacks-Documentation.pdf](https://github.com/mb1986/rm-hacks/files/14025530/rM-Hacks-Documentation.pdf)

**Comment by PepikVaio** [comment]
Would be greate.

**Comment by dreadful-brain** [comment]
> Obsidian does a better job, though I'm still struggling with images being orphaned from their description.
> 
> [rM-Hacks-Documentation.pdf](https://github.com/mb1986/rm-hacks/files/14025530/rM-Hacks-Documentation.pdf)

But unfortunately no TOC-Bookmarks and internal links are not working in this version, the functionality of pandoc was better.

**Comment by knox-dawson** [comment]
> Thanks! Looks great :-) Could this be added (and kept updated) as "Documentation" here on the config page?? !

The docs for 0.0.9 are here https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation, is that what you mean? (alpha-6 ... alpha-7 soon come)

**Comment by Tissefantonsen** [comment]
[knox-dawson](https://github.com/knox-dawson)
Hi, my thought was to have the documentation included in the "configuration settings" for the hack, below the "stylus configuration"...

**Comment by knox-dawson** [comment]
This will probably be my last effort for version 0.0.8.

[rm-hacks-documentation-toc2.pdf](https://github.com/mb1986/rm-hacks/files/14029573/rm-hacks-documentation-toc2.pdf)

**Comment by knox-dawson** [comment]
The wiki is updated for 0.0.9-alpha.7 https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation

I installed alpha.8, but I'm seeing bugs, so I'm leaving the docs as is for now.

**Comment by knox-dawson** [comment]
PDF version.  The table of contents is way long.  Thinking about that.  There's a shorter TOC on the last page.  I thought that would be the one it would use, but apparently not.  It wants to include every heading at every level.  Still learning ...

[rm-hacks-documentation-0.0.9.pdf](https://github.com/mb1986/rm-hacks/files/14046932/rm-hacks-documentation-0.0.9.pdf)

**Comment by knox-dawson** [comment]
The wiki is updated for 0.0.9-alpha.10 https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation

**Comment by Eeems** [comment]
I would highly recommend pointing at the existing community documentation for SSH access: https://remarkable.guide/guide/access/ssh.html

**Comment by knox-dawson** [comment]
> I would highly recommend pointing at the existing community documentation for SSH access: https://remarkable.guide/guide/access/ssh.html

I'm thinking you mean in the Installation section? https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation#installation

**Comment by Eeems** [comment]
> > I would highly recommend pointing at the existing community documentation for SSH access: https://remarkable.guide/guide/access/ssh.html
> 
> I'm thinking you mean in the Installation section? https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation#installation

Correct, to that section of the 0.0.9 (and any other) documentation.

> 
> Something like this? ![image](https://private-user-images.githubusercontent.com/154367947/303110627-163e64e1-2e27-4789-806f-81950ca5b07d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzgyODUsIm5iZiI6MTcwNzMzNzk4NSwicGF0aCI6Ii8xNTQzNjc5NDcvMzAzMTEwNjI3LTE2M2U2NGUxLTJlMjctNDc4OS04MDZmLTgxOTUwY2E1YjA3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QyMDMzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGNmZTZhNDYyYTIyNmYzOWExYjRkMmU1MDI4YzNiNTdmODU4NzI0YTczZmQwZTIxZmQzZDBiYTRjNjc2MjY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z78FtiEHEjvF7QTHVLngXZzOJNCq-__8cP-ikcq90wQ)

That looks good to me

**Comment by knox-dawson** [comment]
FYI, I added two pages to the docs:

https://github.com/mb1986/rm-hacks/wiki/Toolbar
https://github.com/mb1986/rm-hacks/wiki/Installation

The toolbar page has more details about rM Hack's features wrt the toolbar.
The installation page simply moves the installation instructions to a separate page.
