### ISSUE TITLE
Idea: Rearrange rm-hacks page settings

### ISSUE THREAD

**Issue by pragmatically-dev** [mb1986/rm-hacks#188]
Could be useful in order to fit more hacks  hehehe

to something like this or similar 
![Untitled (1)](https://github.com/mb1986/rm-hacks/assets/59318726/993d100e-b63f-44f9-ab02-ab7c67e4b251)

As always thank you so much guys

**Comment by atngames** [comment]
We are on it ;)

**Comment by atngames** [comment]
It has been changed in the current release. Should suit your needs 😉
