### ISSUE TITLE
QuickTools Configuration unresponsive in landscape mode and gesture not recognized

### ISSUE THREAD

**Issue by ingatellent** [mb1986/rm-hacks#189]
When using the rm1 in landscape mode (charging port to the left) the toggles in QuickTools Configuration cannot be toggled (nothing happens). It works if I quit settings change the mode to portrait and then go back.

Additionally the gesture to toggle the QuickTools seem not to be working for me (neither in portrait or landscape orientation). I have all custom gestures turned off except for swipe up to enter sleep, but even with this turned off I am not able to activate the gesture for the QuickTools

RM1, 3.9.3.1986 rM Hacks v0.0.9 alpha-7

**Comment by atngames** [comment]
@mb1986 you can assign me to this one as well 🙏

**Comment by atngames** [comment]
fixed in upcoming alpha
