### ISSUE TITLE
connection refused?

### ISSUE THREAD

**Issue by Lebesge** [mb1986/rm-hacks#190]
### system
Windows
### Information in Powershell
root@reMarkable:~# sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)"
Connecting to raw.githubusercontent.com (0.0.0.0:443)
wget: can't connect to remote host (0.0.0.0): Connection refused
###
I have tried many ways to fix it but no consequence. Can someone help me?

**Comment by Lebesge** [comment]
Nothing changes with or without VPN.

**Comment by Eeems** [comment]
It's trying to connect to 0.0.0.0, which is not a remote IP address. Something is interfering with DNS resolution.
Try running `nslookup raw.githubusercontent.com` to see where it's getting the DNS response from, and what it's even responding with.

**Comment by Lebesge** [comment]
> It's trying to connect to 0.0.0.0, which is not a remote IP address. Something is interfering with DNS resolution. Try running `nslookup raw.githubusercontent.com` to see where it's getting the DNS response from, and what it's even responding with.

Thanks for your reply.
### Response
root@reMarkable:~# nslookup raw.githubusercontent.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost.localdomain

nslookup: can't resolve 'raw.githubusercontent.com'

**Comment by Eeems** [comment]
> > It's trying to connect to 0.0.0.0, which is not a remote IP address. Something is interfering with DNS resolution. Try running `nslookup raw.githubusercontent.com` to see where it's getting the DNS response from, and what it's even responding with.
> 
> Thanks for your reply.
> ### Response
> 
> ```
> root@reMarkable:~# nslookup raw.githubusercontent.com
> Server:    127.0.0.1
> Address 1: 127.0.0.1 localhost.localdomain
> ```
> 
> nslookup: can't resolve 'raw.githubusercontent.com'
> ### change
> 
> Today I try to install hacks again and get a different feedback:
> 
> ```
> root@reMarkable:~# sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.6
> wget: bad address 'raw.githubusercontent.com'
> ```
> 
> I'm quite confused about it and hope you can solve it. Thanks.

For some reason, it's using a local service to do DNS resolution, and that service is returning 127.0.0.1 (localhost). This means you are asking the rM to download the file from itself, which won't work. Have you restarted the device recently at all?

**Comment by Lebesge** [comment]
Yes, I have just restarted my rM1 but nothing changes.

**Comment by Eeems** [comment]
What OS version is your device running?

**Comment by Lebesge** [comment]
3.9.3.1986

**Comment by Eeems** [comment]
What does `cat /etc/resolv.conf` return?

**Comment by Lebesge** [comment]
```
root@reMarkable:~# cat /etc/resolv.conf
# Generated by dhcpcd
# /etc/resolv.conf.head can replace this line
# /etc/resolv.conf.tail can replace this line
```

**Comment by Eeems** [comment]
So this would be why, your device isn't resolving anything. For some reason, it's not getting a DNS server to use from your router. You can put the following in the file to use cloudflare to resolve DNS message:
```
nameserver 1.1.1.1
```

**Comment by Lebesge** [comment]
It occured to me that I downgraded my version according to https://github.com/ddvk/remarkable-update:
![image](https://github.com/mb1986/rm-hacks/assets/131115024/4465bdf1-402f-4017-8144-ed23f1f81b10)
Maybe it's the reason?

**Comment by Lebesge** [comment]
> So this would be why, your device isn't resolving anything. For some reason, it's not getting a DNS server to use from your router. You can put the following in the file to use cloudflare to resolve DNS queries:
> 
> ```
> nameserver 1.1.1.1
> ```

Which file should I put it in?

**Comment by Eeems** [comment]
> It occured to me that I downgraded my version according to ... Maybe it's the reason?

This would be the exact same as doing an official update, so no, it's not the reason. For future reference there is a newer easier mechanism to do this: https://remarkable.guide/faqs.html#can-i-downgrade-to-a-different-os-version


> Which file should I put it in?

`/etc/resolv.conf`

**Comment by Lebesge** [comment]
OK, thanks for your recommendation. I try again and response with:
```
root@reMarkable:~# sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.6
Connecting to raw.githubusercontent.com (185.199.108.133:443)
wget: note: TLS certificate validation not implemented
```

**Comment by Eeems** [comment]
Yes that's expected. Does it output more? It should continue with the installation from there.

**Comment by Lebesge** [comment]
Oh, it's very slow and stuck into
```
root@reMarkable:~# sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.6
Connecting to raw.githubusercontent.com (185.199.111.133:443)
wget: can't connect to remote host (185.199.111.133): Connection timed out
```

**Comment by Eeems** [comment]
This is different output than you provided before. Previously it was saying that TLS was not implemented, and there would be further output from there. Now you are showing output where it's timing out connecting to the server. This appears to be issues with your network, it would be worth going through some of the troubleshooting steps here: https://remarkable.guide/faqs.html#my-device-is-connected-to-wifi-but-can-t-sync-or-check-for-updates-how-can-i-fix-this

**Comment by Lebesge** [comment]
It maybe results from my internet and I almost know what to do. Thanks to your patient guide.

**Comment by Lebesge** [comment]
> This is different output than you provided before. Previously it was saying that TLS was not implemented, and there would be further output from there. Now you are showing output where it's timing out connecting to the server. This appears to be issues with your network, it would be worth going through some of the troubleshooting steps here: https://remarkable.guide/faqs.html#my-device-is-connected-to-wifi-but-can-t-sync-or-check-for-updates-how-can-i-fix-this

Yes, you prensent some useful information and I appreciate it. I will try it again and I think I can solve it. Thanks.

**Comment by atngames** [comment]
@Lebesge following your last sentence two weeks ago, I close this issue.
You are welcome to open it again if you need it.
