### ISSUE TITLE
Swipe one finger down in the top right corner (right-handed)/left corner (left-handed) to swap the last two pen thicknesses (strokes).

### ISSUE THREAD

**Issue by zelomel** [mb1986/rm-hacks#193]
Hello,

I'm left handed. 
The swipe area for swapping the last two pen thicknesses, top left corner for me (left handed), is a little bit too on the right comparing to the swipe area for swapping the last two colors.

Maybe a photo will be more explicit.
![image](https://github.com/mb1986/rm-hacks/assets/64229778/77d242df-2104-453b-b1dc-a5a8e5346b90)

**Comment by zelomel** [comment]
It seems to be linked with close button (x) hidden or not

**Comment by mb1986** [comment]
Hm, it should be exactly the same area but probably some wrong calculation of it :grimacing:

**Comment by atngames** [comment]
Hi, is this fixed in the current release?

**Comment by zelomel** [comment]
Yes !
Thank you for your work.

**Comment by atngames** [comment]
👍
