### ISSUE TITLE
Installing the hack via iPhone

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#194]
Hi, I created an iPhone shortcut to install rm-hack.
@mb1986 Is there any way I can add this to the project?

Here is a sample:
https://www.youtube.com/watch?v=9EfUzZxOQcA

**Comment by Eeems** [comment]
The link goes to https://github.com/mb1986/rm-hacks/issues/url

**Comment by Eeems** [comment]
The link you posted isn't to the youtube video, try clicking it.

**Comment by PepikVaio** [comment]
I fixed it :)
Sorry and thank you.

**Comment by mb1986** [comment]
What do you think about adding it to the wiki? It is publicly editable. @knox-dawson is managing it though.

**Comment by knox-dawson** [comment]
I'm managing it to the extent that I'm working to keep it up to date.  I think I'll finish 0.0.9-alpha.7 soon (and now there's alpha.8 to look at).

That said, there's no reason you can't add a page for the phone shortcut.

**Comment by PepikVaio** [comment]
How do you mean add a page?
Write instructions on how to create a shortcut?

I thought I would directly put the shortcut somewhere where the bridge will be downloaded directly.

**Comment by knox-dawson** [comment]
What I meant was to go here https://github.com/mb1986/rm-hacks/wiki and click New Page.  Then you add markdown text.

As for "put the shortcut somewhere where the bridge will be downloaded directly" that's outside my area of understanding.

**Comment by PepikVaio** [comment]
@knox-dawson is it OK?

[Wiki](https://github.com/mb1986/rm-hacks/wiki)
[Install rm-hacks using iPhone](https://github.com/mb1986/rm-hacks/wiki/Install-rm%E2%80%90hacks-using-iPhone)
