### ISSUE TITLE
In 0.0.9-alpha.8 the "Show current brush icon" is missing on the Document Settings page

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#196]
Is this intentional because of the QuickTools bar?  If so, I'd argue for bringing it back.

![image](https://github.com/mb1986/rm-hacks/assets/154367947/4d4f270b-ce03-416c-9d65-7cb3f9c4268d)

![image](https://github.com/mb1986/rm-hacks/assets/154367947/353667f1-21bf-4ca7-a8dc-33bb5f4171dc)

**Comment by rudy0ne** [comment]
It's still showing in document settings for me, and I'm also on alpha 8

**Comment by Kelvin88** [comment]
It’s always been like that. Hiding toolbar button will show current tool.

**Comment by knox-dawson** [comment]
Sorry, my bad.  I usually do have the hide option off, so I lost track of that detail, thanks.

[Resolved]
