### ISSUE TITLE
Automatically retry downloads

### ISSUE THREAD

**Issue by Eeems** [mb1986/rm-hacks#197]
I'm trying to install right now, and I'm getting `error writing output file` while part way through downloading a patch, which results in `Cannot write to ‘-’ (Success).` and the script exiting. Trying again means that it has to start over, and doesn't retry, or continue from where it was previously in the download.

It would be worth using some of the retry flags in wget to automatically retry just in case the failure is transient.

Reworking the script so that `--continue` can be used to continue downloading a partial file would also be a good idea. For the patch files. You could use mktemp to create a temporary directory to download into that you can clean up at the end.

**Comment by atngames** [comment]
I agree it would be useful.

This will probably not happen right now, but after release 0.0.9, we'll see ?

**Comment by mb1986** [comment]
Could you please confirm that it would be `-c` switch?

```sh
reMarkable: ~/ wget                                                                                                                                
BusyBox v1.35.0 () multi-call binary.

Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header STR]
	[--post-data STR | --post-file FILE] [-Y on/off]
	[-P DIR] [-U AGENT] [-T SEC] URL...
```

**Comment by mb1986** [comment]
Yes, this is what I've seen too, I'll use `-c` for now as we have mixed `wget` versions. Thanks!
