### ISSUE TITLE
QuickTools configuration toggles not working in Landscape when Large font is selected (0.0.9-alpha.8)

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#198]
In rM Hacks version 0.0.9-alpha.8, if I select the Large Font size in the remarkable Accessibility settings AND if I select either landscape mode with the screen orientation button, none of the toggles in the rM Hacks QuickTools Configuration panel seem to work.

**Comment by atngames** [comment]
fixed in upcoming alpha

**Comment by knox-dawson** [comment]
Confirm fixed in alpha.10
