### ISSUE TITLE
With the addition of QuickTools, does there need to be a "Gesture to toggle QuickTools" toggle in the Gestures Configuration panel?

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#199]
There is a toggle for Gesture to toggle toolbar (one finger down in center), but there doesn't seem to be a Gesture to toggle QuickTools (one finger up in center).

**Comment by atngames** [comment]
Yes it will be added to solve a few issues here

**Comment by atngames** [comment]
#189

**Comment by atngames** [comment]
fixed in upcoming alpha

**Comment by knox-dawson** [comment]
Confirm new setting in alpha.10
