### ISSUE TITLE
Is there a feature roadmap and place to request features?

### ISSUE THREAD

**Issue by Tridens92** [mb1986/rm-hacks#20]
Hi, I'm a long-time ddvk rmhacks user that has been avoiding updating my rM1 to v.3.x.   I'm **really** excited about this new project!  Before I make the (seemingly) irreversible jump to v.3.x and this hack, is there:

1) a roadmap of upcoming features?
2) a preferred place / way to make suggestions?  I believe the Discord group is intended for developers (not mere users like myself), so I didn't want to post this there.

Thanks!

**Comment by mb1986** [comment]
Hi @Tridens92, I'm excited too! I'd love to fulfill everyone's needs - unfortunately, probably not possible. Regarding your questions - I think GitHub issues are a good place to raise new feature requests. What do you think? There isn't a formal roadmap, but I'll start implementing things, beginning with the easiest or the most requested ones. :)

You are very welcome!

**Comment by Tridens92** [comment]
That sounds great, @mb1986 !  Another option would be to use something like Trello, which keeps track of votes, etc.  https://blog.trello.com/3-ways-to-manage-feature-requests

**Comment by Eeems** [comment]
Github already lets people react to open issues, and has projects for a trello like interface for tracking progress, as well as planning. I'd recommend against adding another place for information to be stored.

**Comment by Tridens92** [comment]
> Github already lets people react to open issues, and has projects for a trello like interface for tracking progress, as well as planning. I'd recommend against adding another place for information to be stored.

Thanks!  I'm not a developer and am not super familiar with Github's features.

**Comment by mb1986** [comment]
Thanks for the comments, I'd stick to Issues only for now as I think this project is too small for GitHub Projects. Let's see how it will work. We can always enable projects when needed.
