### ISSUE TITLE
Add toggles to choose clock position.

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#201]
As of version 9.0.0-alpha.10, there are two places to toggle the clock on and off (in rm-hacks settings and the one inside the share menu). Please change the rm-hacks setting to a toggle which moves the clock from the toolbar to the opposite top corner and vice versa. 

Plus, a second toggle to choose between the top and bottom corners would be great, especially since the clock currently gets in the way of the bookmark icon on the top corner.

**Comment by atngames** [comment]
For now, the clock is back on the top of the toolbar, where it should be. (fixed in next alpha)
The configurable tollbar objects placement might come in a future version of rmhacks
