### ISSUE TITLE
Highlight the selected tool even if it’s not on the QuickTools panel

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#203]
In version 9.0.0-alpha.10, whichever tool is currently selected is highlighted on the QuickTools panel if it is saved as one of the shortcuts. But when the selected tool or its specific color and stroke size combination is not on the panel, it would make sense for the selected tool as it appears on the top corner to become highlighted if the QuickTools panel is open.

![Screen Shot 2024-01-30 at 1 44 43 PM](https://github.com/mb1986/rm-hacks/assets/22302732/69bd0bf9-7efa-45cd-9ebe-ea25bd526a62)

**Comment by atngames** [comment]
Okay it should be implementend in next alpha. Thanks for the idea !

**Comment by mb1986** [comment]
Is it already implemented?

**Comment by atngames** [comment]
I think that whenever I wrote "should be implemented in next alpha", it is because I did fix it and created a commit. So it is working (hopefully) properly in alpha 11

**Comment by rudy0ne** [comment]
It's not working in alpha 12 which I just installed. It's kind of doing the opposite, highlighting it when the selected tool/color/size is part of the QuickTools panel but not when it's not.

https://github.com/mb1986/rm-hacks/assets/22302732/fda4c115-4cde-448e-b304-7107c302dd7e

**Comment by atngames** [comment]
Hmmm yes, wrong boolean test, I did not understand that well apparently :D
This was an easy fix and will be applied very soon

**Comment by rudy0ne** [comment]
This is now fixed in alpha 13 🙌

And also (at least while the QuickTools panel is open) it solves another issue I brought up in the Discord, which is the problem of dark page backgrounds covering the selected tool:

![IMG_4171](https://github.com/mb1986/rm-hacks/assets/22302732/77e49050-01b0-43cd-a688-bac99e8d6cc1)
