### ISSUE TITLE
Show current brush icon BG not working when toolbar not decreased

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#204]
When the toolbar is normal size (not decreased) and the "Show current brush icon BG" is OFF, the BG color continues to display

![image](https://github.com/mb1986/rm-hacks/assets/154367947/4865f7e9-4890-45c9-96d6-68d6ae2c4555)

![image](https://github.com/mb1986/rm-hacks/assets/154367947/72af48a6-a0e2-4aaa-9151-53d9f06f5421)

![image](https://github.com/mb1986/rm-hacks/assets/154367947/9032e582-d403-4713-96da-9aa10e2fe5e6)

**Comment by atngames** [comment]
Okay this will be fixed in next alpha

**Comment by atngames** [comment]
Yeah I think so
We have had a whole lot of bug correcting lately, we are a bit lost on all this, I think my last message was written after fixing it, before the PR was reviewed.

**Comment by atngames** [comment]
Just tested it and yeah it works

**Comment by knox-dawson** [comment]
Confirm fixed in alpha.14
