### ISSUE TITLE
QuickTools disappears when vertical and covered by toolbar.

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#211]
(0.0.9-alpha.10)
When the QuickTools bar is vertical and does NOT hide behind the toolbar, you can open and close the toolbar and the QuickTools stay visible.

But when it DOES hide behind the toolbar, when you open and close the toolbar, the QuickTools disappear.

So:
  - What it does: QuickTools go away when hidden by toolbar
  - What I want: QuickTools hides behind toolbar, but reappears when toolbar closes

![image](https://github.com/mb1986/rm-hacks/assets/154367947/6919eae3-8a78-42ba-91c2-5ca9617f6e42)

QuickTools show:
![image](https://github.com/mb1986/rm-hacks/assets/154367947/91d91cdb-892c-4ca3-8dc9-e4a5e2bdd1c2)

Toolbar open:
![image](https://github.com/mb1986/rm-hacks/assets/154367947/c1ab1aab-7ddd-4090-9991-647f6f5a2f88)

Toolbar close (QuickTools still show):
![image](https://github.com/mb1986/rm-hacks/assets/154367947/91d91cdb-892c-4ca3-8dc9-e4a5e2bdd1c2)

When it DOES hide behind the toolbar, when you open and close the toolbar, the QuickTools disappear.

![image](https://github.com/mb1986/rm-hacks/assets/154367947/3dbe1910-a54b-4a79-ac46-77da51789ac2)

QuickTools show:
![image](https://github.com/mb1986/rm-hacks/assets/154367947/91d91cdb-892c-4ca3-8dc9-e4a5e2bdd1c2)

Toolbar open (QuickTools hidden):
![image](https://github.com/mb1986/rm-hacks/assets/154367947/e070d907-f2e0-4800-9e9e-118eb52c5714)

Toolbar close (QuickTools don't show):
![image](https://github.com/mb1986/rm-hacks/assets/154367947/091cd893-9995-43a6-b3fa-87a3359a57bd)

**Comment by atngames** [comment]
Of course! I'll look into it

**Comment by atngames** [comment]
Ok should be fine in the next alpha

**Comment by knox-dawson** [comment]
Confirm fixed in alpha.14 (I never loaded 11-13)

Thanks!!
