### ISSUE TITLE
Enable or add a screenshot feature, fullscreen and selected area

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#212]
**From #205** 

> * [ ]  **(13)** Take a screenshot **[Ctrl + Shift + 3]**
> * [ ]  **(14)** Lets you select and screenshot a portion of the screen **[Ctrl + Shift + 4]**
> 
> _I would love those shortcuts for screenshots, similar to what I use on my Mac._

If I’m not mistaken, you mentioned that there’s a native experimental screenshot feature. Hopefully that means that this wouldn't be too difficult 😁

**Comment by pragmatically-dev** [comment]
I really hope that the screenshot could be converted to rmlines (I don’t really know), but maybe the experimental functionality just take the current page and just let you send it through Email interface :(

Maybe atn or mb could give us some insight

**Comment by atngames** [comment]
The fullscreen screenshot is doable, the partial screen one seems complicated to me.
It is possible to export as png in the devices' /home/root or as pdf in the Files folder.
I don't think it would be possible to export as rmlines as is.
Let's add this for the next milestone ;)

**Comment by rudy0ne** [comment]
I'm totally fine with individual pngs

**Comment by mb1986** [comment]
I think this is one of native (but disabled) features. Should be doable.

**Comment by PepikVaio** [comment]
> The fullscreen screenshot is doable, the partial screen one seems complicated to me.
> 
> It is possible to export as png in the devices' /home/root or as pdf in the Files folder.
> 
> I don't think it would be possible to export as rmlines as is.
> 
> Let's add this for the next milestone ;)

Please make it so that the "screenshots" folder is automatically created.
Thank you.

**Comment by rudy0ne** [comment]
> ...the partial screen one seems complicated to me.

Maybe it’s not the most efficient way of doing the partial screenshot, but if it proves too difficult via the use of a selection tool then how about giving the following way a try: If we open a split view of only a small fraction of the same page, theoretically, could we not take a screenshot of only whatever appears in that small split view? @mb1986 @atngames 


![Screen Shot 2024-02-03 at 7 03 09 PM](https://github.com/mb1986/rm-hacks/assets/22302732/e35c0e41-fe7e-40c4-a970-27e114e634f1)

**Comment by mb1986** [comment]
I've just verified and it would be easy to enable a full page screenshot into PNG saved in `/home/root` or PDF added to the documents (My Files).

**Comment by pragmatically-dev** [comment]
This would definitely open new doors to convert that screenshot to rmlines by using Drawj2d and rmapi in the device, as someone already could run drawj2d in the device with java [Here the comment](https://www.reddit.com/r/RemarkableTablet/comments/nawmzm/comment/gydvglx/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button)

**Comment by atngames** [comment]
For reference https://github.com/mb1986/rm-hacks/issues/216

**Comment by PepikVaio** [comment]
Alpha 0.0.10 - Fork fine :)
Please add so I can set the folder where the screenshots will be saved (for example, the "screenshots" folder)

**Comment by qwert2003** [comment]
> This would definitely open new doors to convert that screenshot to rmlines by using Drawj2d and rmapi in the device, as someone already could run drawj2d in the device with java [Here the comment](https://www.reddit.com/r/RemarkableTablet/comments/nawmzm/comment/gydvglx/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button)

If you do the conversion from png (or pdf) to rmlines on the device then you do not need rmapi. Java (JRE) and Drawj2d should be enough.
By the way, the current release of drawj2d (1.3.3) supports the output type _rmdoc_ (reMarkable notebook files in a zip). It might work to just unzip the file out.rmdoc to get a new notebook with the converted screenshot.
