### ISSUE TITLE
Add Hebrew Support to reMarkable

### ISSUE THREAD

**Issue by Yaniv-Kaplan** [mb1986/rm-hacks#214]
Add Hebrew support in the Tablet. Mostly for rendering file names.

I don't know how difficult of a change this is to implement, but I would also gladly help.

**Comment by mb1986** [comment]
Do you think it would be done on the font level? If so then our _next_ approach to the hacks would be able to change the font and bring Hebrew that way. Nonetheless, it is not an easy task for now.

**Comment by Jayy001** [comment]
Would this require a font change?
