### ISSUE TITLE
Bookmarks orphaned after moving pages out of Notebook

### ISSUE THREAD

**Issue by somedaygone** [mb1986/rm-hacks#218]
I had 2 pages with bookmarks. I selected them and moved them out of the Notebook. The bookmarks still exist as page “0”. I can’t find a way to delete them.

![IMG_8429](https://github.com/mb1986/rm-hacks/assets/4382563/9a609514-652a-47a3-97be-30941c5797af)

rm-hacks  v0.0.8
rM version 3.9.3.1986

**Comment by knox-dawson** [comment]
I see it in 0.0.9-alpha.10.  Wild.

**Comment by atngames** [comment]
@mb1986 Maybe this needs attention before release ?

**Comment by mb1986** [comment]
The fix will be applied in the next alpha.

**Comment by mb1986** [comment]
Should be fixed in alpha.12:

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.12
```
