### ISSUE TITLE
Change blue text color used in installation script

### ISSUE THREAD

**Issue by mb1986** [mb1986/rm-hacks#22]
As it has been pointed out by @dreadful-brain in issue #9 blue color may be annoying for people having blue background in the console:

> The only thing that is a bit annoying is the blue texts in the install script.
Since on Windows the default background color of the most common SSH tool Putty is black, you have to change it first to be able to read the questions.
For me this is not a problem, because I use Putty regularly, but it could be a hurdle for some people.
Suggestion: use cyan (0,255,255) instead of blue text.

**Comment by Eeems** [comment]
You could also set the background colour specifically in your script as a less pretty measure, but at least it will all look as expected.

**Comment by mb1986** [comment]
I've changed it to cyan for now (https://github.com/mb1986/rm-hacks/pull/27). If there will be more issues related to those colors I will change the background.
