### ISSUE TITLE
folder navigation

### ISSUE THREAD

**Issue by srshouston** [mb1986/rm-hacks#220]
was able to install the ssh code; everything works as expected but unable to navigate to folder or exit the file once I open

**Comment by mb1986** [comment]
To close the document please swipe one-finger down from the very top of the screen (in the center of the screen.

**Comment by PepikVaio** [comment]
Maybe it would be better not to have hard hacks enabled after installation.
And let the user know what's new.

Like reMarkable - after reboot it will show a screen what's new.

**Comment by mb1986** [comment]
I love the idea, possibly in the future...

**Comment by srshouston** [comment]
> y flipping switch in the settings (rM Hacks section).

This helped. thanks

**Comment by srshouston** [comment]
> ou may bring back the (x) icon by flipping switch in the settings

Hi - how do I find rmHack section in settings per your message _"you may bring back the (x) icon by flipping switch in the settings"_

**Comment by mb1986** [comment]
> Menu -> Settings -> rM Hacks -> Document Configuration -> Hide document close button (x)
