### ISSUE TITLE
Navigation panel - Bug

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#224]
**I have reported this bug:**
https://github.com/mb1986/rm-hacks/assets/36114753/c1deb866-61c2-47b4-813c-78df443cf70e

**Repairs have been made:**
https://github.com/mb1986/rm-hacks/assets/36114753/99e6d3f8-c58d-4d3c-836f-209f15a0e285

**But original is this:**
https://github.com/mb1986/rm-hacks/assets/36114753/5fa45c8d-1b67-4cc0-9ab4-96bbb5da4d11

**Comment by atngames** [comment]
I think this has been solved in a previous version.

The icon has a transparent background if we show the brush icon and a white background if it is the round toggle icon.
I am closing this, feel free to open it again if you feel it is not completely fixed !

**Comment by PepikVaio** [comment]
Please watch the original video again.
When the panel is closed, the area of ​​the wheel is minimal.
Takes up a lot of space when open.

In fiction, the area covers part of the text.
This does not happen in the original, because it is a much, much smaller area.

**Comment by atngames** [comment]
Ok

**Comment by PepikVaio** [comment]
Fixed in alpha 10 :)
