### ISSUE TITLE
Disable Native borders on PDF zooming

### ISSUE THREAD

**Issue by pragmatically-dev** [mb1986/rm-hacks#225]
Hi! Is it possible to remove the added border line when zooming a PDF or EPub? 

![image](https://github.com/mb1986/rm-hacks/assets/59318726/af135124-0033-4ea2-bab0-63c8e78ac53b)

When zooming it appears:
![image](https://github.com/mb1986/rm-hacks/assets/59318726/9f4ca492-0e12-4642-a04d-190dca23c394)

Solving this problem would also solve the problem of the overflowing lines on SplitDoc feature 

![image](https://github.com/mb1986/rm-hacks/assets/59318726/96cc187b-1aff-462d-95da-342961d50723)

and here the overflow:

![image](https://github.com/mb1986/rm-hacks/assets/59318726/506beea6-0b28-40f9-8b06-143ecfe87d6d)

As always I’d like to thank you guys, what you have achieved is amazing!

**Comment by atngames** [comment]
Hi i will look into this pretty soon
Seems doable, though

**Comment by pragmatically-dev** [comment]
That’s nice!

**Comment by atngames** [comment]
We'll see 😅

**Comment by hakunamatatarr** [comment]
Sorry, one question: What is this SplitDoc feature you show there?

**Comment by atngames** [comment]
I am working on a split screen feature and had a prototype tested two weeks ago. 
It will be a bit more polished and released as alpha maybe next week-end or the week after.
Stay tuned

**Comment by hakunamatatarr** [comment]
That is great! I just installed rm-hacks and I love it! So far I thought to switch to the new Supernote when it comes out but this might have changed the situation. Thank you for the awesome work!

**Comment by mb1986** [comment]
Thanks for the kind words :blush:

**Comment by atngames** [comment]
Okay this feature is done and will be included in the next alpha for 0.0.10.
There will be a toggle, off by default.
Cheers

**Comment by PepikVaio** [comment]
Alpha 0.0.10 - Looks good :)
