### ISSUE TITLE
QuickTools config confusing or bug?

### ISSUE THREAD

**Issue by RedTartan04** [mb1986/rm-hacks#227]
Just tried out 0.0.9 - ace!
I'm a little confused by the various QuickTools settings - maybe it's just the wording.
I tried to get the QuickTools inside the toolbar above the other tools like in this screenshot but it'll always be next to the toolbar
https://github.com/mb1986/rm-hacks/wiki/QuickTools#quicktools-hides-behind-the-toolbar-when-quicktools-is-vertical
I only have enabled "QuickTools bar" and the two "details" switches.
Changing "hides behind" seems to have no effect.

**Comment by knox-dawson** [comment]
I'm guessing a bit here.  Hides behind: selected.

First,
  - When the toolbar is open, swiping up will open and close the quicktools next to the toolbar.
  - When the toolbar is closed, swiping up will open and close the quicktools in the toolbar location.

Second,
  - When both the toolbar and quicktools show side by side, closing the toolbar will move quicktools to the toolbar location
  - Then opening the toolbar should place the toolbar OVER the quicktools, and
  - Then closing the toolbar should uncover and display quicktools again.

Does that not happen for you?

**Comment by knox-dawson** [comment]
This page has changed https://github.com/mb1986/rm-hacks/wiki/QuickTools#quicktools-hides-behind-the-toolbar-when-quicktools-is-vertical.

Whether or not it is more clear, it is at least more accurate.

**Comment by RedTartan04** [comment]
Thanks! It's sad the change was intentional :/ There's so much empty space in my toolbar.

The doc still says "If true, QuickTools is horizontal on top, otherwise it will be **vertical below or** next to the toolbar." - it's always next to it, that's what you meas has changed, right? and you missed to update this sentence? 🤪

**Comment by knox-dawson** [comment]
> Thanks! It's sad the change was intentional :/ There's so much empty space in my toolbar.

I _think_ the change was intentional, but I could be wrong.  I've run out of space in my toolbar in landscape mode.

![image](https://github.com/mb1986/rm-hacks/assets/154367947/935b5107-9431-4577-b94f-691e011ba921)


> The doc and the settings still say "If true, QuickTools is horizontal on top, otherwise it will be **vertical below or** next to the toolbar." - it's always next to it, that's what you mean has changed, right? and you/they missed to update this sentence? 🤪

Hmm, I can change the docs.   I think I'll compile a list of menu wording that might need changes and I'll include that.

**Comment by RedTartan04** [comment]
Ah, saw your wording collection. In my understanding (not a native speaker) "below" means it's downwards, i.e. the quicktools would be further down the screen, while "under" means it's in this case behind the toolbar. 

Here's what my toolbar looks like 
![](https://github.com/RedTartan04/rmGesturesDoc/blob/main/rm-hacks%20gestures.png) so I thought it would make sense to position the quicktools inside the toolbar strip. :)
