### ISSUE TITLE
[Lamy - Tool Switch] Only works on different tools, not colors

### ISSUE THREAD

**Issue by hmenzagh** [mb1986/rm-hacks#230]
First of all thanks for the great work, this repo has given a second life ton my Remarkable !

I dont know if that's a new issue with 0.0.9 or a long standing one. But when using tool switching, it will only switch between different types of pens, not colors.

**Comment by mb1986** [comment]
Do you mean that while switching tools the color is not properly switched? I think it may be the case :grimacing:
