### ISSUE TITLE
Screen sharing even in the main menu

### ISSUE THREAD

**Issue by dreadful-brain** [mb1986/rm-hacks#232]
Currently, reMarkable screen sharing only works in documents, as soon as you are in the main menu, no screen is transferred. However, if you open another document, the session continues.
Could you check whether it might be possible to change this with little effort so that the screen transfer also works in the main menu? The alternatives with vnc, e.g. rmview, no longer work with the 3 firmware, or only in the same way as normal screen sharing.
It would be cool if you could use a switch to control whether the directory listing should also be transferred.

**Comment by ZacharieALES** [comment]
Restream still works for me:
https://github.com/rien/reStream

**Comment by dreadful-brain** [comment]
> Restream still works for me: https://github.com/rien/reStream

Thank you, I will try it.

**Comment by dreadful-brain** [comment]
I tested it in 0.0.10-alpha.1 / 3.9.4.2018 on rM2 with and without TypeFolio in all resolutions and rotations.
It works as expected. 

There are IMO these (native) limitations:
1. You can start screen share from a document only
2. If already started, screenshare is active even in settings, but you cannot disconnect there
3. In main menu, you see the notification "Open a document to continue presenting" even if you have "ScreenShare everywhere" switched on,

1. and 2. are IMO in order, just something for the docs
3. could be improved by only showing the notification if the "ScreenShare everywhere" switch is off.

**Comment by dreadful-brain** [comment]
I would vote that you also list this switch in the switches section of the document.

My Use Case:
I use ScreenShare a lot in meetings and usually I don't want the directory listing to be shown unless I deliberately want to show someone the reMarkable. 
If the switch is in the document, I can check it briefly before I switch to another document and inadvertently reveal my file structure.
In the opposite case, I can also simply activate this function. There are currently 2 options for this, neither of which is ideal:
- Either quit ScreenShare, activate Switch and go back to the document and restart ScreenShare.
- Activate the switch during active ScreenShare, but then ScreenSharing is continued in the hacks settings.

**Comment by PepikVaio** [comment]
Alpha 0.0.10 - Work fine, but for security reasons, I'm not enabling this feature.
