### ISSUE TITLE
Bookmarks are lost when leaving the notebook.

### ISSUE THREAD

**Issue by dafxy** [mb1986/rm-hacks#237]
PDFs hold the created bookmarks, but notebooks do not. The notebook's bookmarks disappear upon closing and reopening them.

**Comment by mb1986** [comment]
I've just tested and on my end and I cannot reproduce the issue... Works for both PDFs and notebooks.
It is important that `xochitl` runs with `QML_XHR_ALLOW_FILE_READ=1` and `QML_XHR_ALLOW_FILE_WRITE=1` environment variables.

Could you please verify that you have them properly setup:
```sh
cat /etc/systemd/system/xochitl.service.d/qmlfileops.conf 
```
The `qmlfileops.conf` file should contain:
```
[Service]
Environment="QML_XHR_ALLOW_FILE_READ=1"
Environment="QML_XHR_ALLOW_FILE_WRITE=1"
```
Do you use any launchers that may possibly cause this issue?

**Comment by dafxy** [comment]
My `qmlfileops.conf` file matches your description. Not sure about the launcher. How do I check that?

**Comment by mb1986** [comment]
I mean one of those: https://remarkable.guide/guide/software/launcher.html. Do you use them?

**Comment by dafxy** [comment]
I am not using any of those, only the default.

**Comment by dafxy** [comment]
I noticed that it is working on other new notebooks. After I copied all the content to another notebook, it worked.

**Comment by txoof** [comment]
RM 2, V3.11.2.5 (rM Hacks v0.0.10)

I experienced this today and I can't seem to reproduce it in another notebook, but I have a notebook file that will no longer accept bookmarks. The only bookmarks that appear are `First Page` and `Last Page`. Adding bookmarks to this works until the document is closed. Upon reopening the document, all the bookmarks are gone except for `First` and `Last`.

Inspecting the documents on the remarkable shows that the `.bookm` file still contains all the expected bookmarks (see below). 

@mb1986 is there a process that I could use to recover these? It's a real bummer to lose all of those bookmarks. I can zip up and share the document and associated files with you if that's helpful. I'd rather not post it here.

`cat 1c21f516-665a-4089-8191-9338ffeb12c1.bookm`
```
{"6b1c7dea-469e-41b0-a75d-f550559fceb8":{"name":"March 24"},"a5e3ce60-a569-4a5c-9ede-5b9a37d6463c":{"name":"Future log"},"b0d7962a-af6d-4b5a-951c-65c5a948ddbc":{"name":"VU registration"},"b35c60da-f73f-43c3-961b-4eb911bc0be0":{"name":"April 24"},"fd749135-05c1-4c35-95fc-0934bb1825a2":{"name":"House Repairs"},"af09d9ad-ed29-46d3-a144-6bdba0a97353":{"name":"Expenses"},"194c77d9-cb85-43e0-a0eb-751f1238e46d":{"name":"May 24"},"68e56ed7-a073-434a-87a0-86a658d24ee7":{"name":"Vacation 2024"},"406a52dd-3d0f-4c00-ad05-f04c42c6e380":{"name":"June 24"},"e9ef6ec7-7a9e-4a2e-a475-f907e05e2ada":{"name":"Bresda Call"},"f7bbc68a-8b06-4986-a12a-2a59907b3543":{"name":"Packing"},"aad58667-077b-4a97-af2b-ac536b1edbaa":{"name":"Cycle tour"},"040cb0ae-05f2-4e89-967e-564a9d5ba1ec":{"name":"Learn"},"73a18f9d-8a0e-4757-ad70-edb07b41b52a":{"name":"Shop/Pickup USA"},"8aeb7566-f8f3-46d4-a726-323c18a852f4":{"name":"cycle packing"},"fea6de1e-1af7-49d8-9897-c356fe11008a":{"name":"July 24"},"c3d57fba-6c83-4e97-b339-d771a5117e4f":{"name":"Lenovo service"},"b978d8e6-8cf9-40c2-83dc-020760e76e4d":{"name":"BUAS Review"},"1ca6311a-644b-44ef-9e8c-4eeba499a416":{"name":""},"a8522a4e-eb59-48c5-9828-0ad67f418122":{"name":"August 24"}}-eb59-48c5-9828-0ad67f418122":{"name":"August 24"}}
```
Metadata:
```
{
    "createdTime": "1710707144888",
    "lastModified": "1722935380360",
    "lastOpened": "1722935382353",
    "lastOpenedPage": 34,
    "parent": "",
    "pinned": true,
    "type": "DocumentType",
    "visibleName": "Personal BuJo"
}
```

**Comment by txoof** [comment]
## Solution for recovering corrupt bookmarks

I managed to recover the bookmarks. It looks like there was a poorly composed item in the index `.bookm` JSON. This last item in the list appears to be causing the problem: `"a8522a4e-eb59-48c5-9828-0ad67f418122":{"name":"August 24"}}-eb59-48c5-9828-0ad67f418122":{"name":"August 24"}}` 

Here are the steps for recovering if anyone else gets stuck:

1. Export the notebook (use RCU or tar up the all the appropriate files and sftp them somewhere should also work: `tar cvzf ./deadbeef-0000-1234*`)
2. Rename the existing document on the Remarkable - this ensures that you won't overwrite the original if you do something awful!
3. Un-tar the `.rmn` (`tar xvzf MyNotebook.rmn`
4. Open the `.bookm` document and look for poorly formatted bookmark item (see below for bookmark format)
5. Remove the problematic string, save and tgz the document (`tar cvzf MyDoc.tgz ./*`)
6. Send the document to the remarkable

Bookmark expected format (displayed on multiple lines for readability- **NOTE: this should all be a single line with no unquoted spaces!**
```
{
    "f7bbc68a-8b06-4986-a12a-2a59907b3543": {
        "name": "Packing"
    },
    "fd749135-05c1-4c35-95fc-0934bb1825a2": {
        "name": "House Repairs"
    },
    "fea6de1e-1af7-49d8-9897-c356fe11008a": {
        "name": "July 24"
    }
}
```

**Edit:** If you're bold, I suppose you could edit the `.bookm` file on device.
