### ISSUE TITLE
QuickTools panel and the selected tool icon should appear in text mode

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#239]
> I first noticed this in v0.0.9-alpha.2 for 3.9.4.2018 and recorded the following videos, but the issue still persists in v0.0.10-alpha.1

Read update below.

https://github.com/mb1986/rm-hacks/assets/22302732/5e645aec-1ff1-4d80-b210-6d5f7a555883

https://github.com/mb1986/rm-hacks/assets/22302732/ccbaea7b-2252-47b6-af82-0f1b92b4a4ac

**Comment by dreadful-brain** [comment]
When you add a new page with TypeFolio attached, you are automatically switched to text mode and QuickTools generally do not appear in text mode.

**Comment by rudy0ne** [comment]
> When you add a new page with TypeFolio attached, you are automatically switched to text mode and QuickTools generally do not appear in text mode.

Great catch! It's my first time noticing that the QuickTools panel and selected tool disappear every time the "T" is selected.

I changed the title, and I believe that they should appear in text mode as well. When I'm in text mode and use a gesture or the stylus button to switch tools I am unable to see if it worked until I actually use the pen. 

And perhaps in text mode the "T" should appear in the corner as the selected tool.

**Comment by atngames** [comment]
Thanks for the report, I'll try to look at this pretty soon

**Comment by atngames** [comment]
Quicktools will stay visible on text mode in an upcoming alpha, it seems to work on my device ;)
