### ISSUE TITLE
Headings and Links

### ISSUE THREAD

**Issue by hakunamatatarr** [mb1986/rm-hacks#241]
Again I would like to thank you for your work! Really enhances the rM experience!
As I said in another thread, I am still waving between the rM and the SN. Two of the features that I think are very useful in the SN are the headings and the links. 
So basically with headings one can mark a part of a note with the lasso tool and set them as heading. They get a different appearance to show them as headings and a table of contents is created with pictures of the headings in a note. I think it is similar to your bookmark feature but somehow nicely implemented with the automatic TOC. 
The links work also by marking something with the lasso tool, then an option for the link appears and one can choose to link to a specific page in the same or in a different notebook. Afterward, the marked part is underlined and gets a link symbol next to it. You can click with the finger on it and it brings you to the linked place (and they actually work on the exported pdf of the note).
This is a nice video to show the implementation and a possible use in SN: [https://www.youtube.com/watch?v=aCiTLnmx6O8](https://www.youtube.com/watch?v=aCiTLnmx6O8)
Now I have no idea how complicated this is to do on a rM and maybe you already thought about it, but I couldn't find the suggestion here, so I thought I bring the idea up. Thanks again!

**Comment by atngames** [comment]
I have no idea if this is feasible on rm yet. I would love to take some time trying to do so.
Pretty unlikely though... :(

**Comment by hakunamatatarr** [comment]
Alright, that's what I thought. Anyway, great that you will have a look at it!

**Comment by Jayy001** [comment]
Closing in favour of #176
