### ISSUE TITLE
can't change screen orientation after using new screen orientation button

### ISSUE THREAD

**Issue by timocarnill** [mb1986/rm-hacks#242]
When you use the screen orientation button in the top right of the documents screen to put the screen in a non-default orientation, the default remarkable button inside the document to change the screen orientation doesn't work, so there's no way to change the orientation.

I would suggest adding the same screen orientation button that's on the documents list to the toolbar. Could also be done with a gesture perhaps, which would make separate controls for left/right easier I think, as it would be nice to not have to cycle through all of them. You could also have two separate buttons, one for rotating right, one for left.

**Comment by atngames** [comment]
Yeah I just saw that yesterday too.
I'll try to work on this cause I need it for another feature.

**Comment by atngames** [comment]
This is fixed in the current alpha
