### ISSUE TITLE
Optional logging of keyboard input for use with background scripts

### ISSUE THREAD

**Issue by plan5** [mb1986/rm-hacks#245]
It would be awesome if there was a way to log keyboard input (temporarily) to a readable file.

This way, custom scripts could be triggered that need keyboard input.

This might be remotely related to https://github.com/mb1986/rm-hacks/issues/61

Specifically I'm thinking about a fix for https://github.com/plan5/remarvin that would allow entering a password without the need of rm2fb. My current implementation renders ~/.local/share immutable. Otherwise I might have considered reading the title from a newly created file, but that's a topic for here: https://github.com/plan5/remarvin/issues/8

**Comment by Eeems** [comment]
If you are looking to remove the dependency on rm2fb, and instead depend on rm-hacks, you will be putting yourself in a similar situation unfortunately, as rm-hacks does need to be updated with each release. As more features are added to rm-hacks, and changes are made to xochitl, updating it gets slower as well. I personally would recommend helping get rm2fb working on newer versions, as that's something that you can work on right now instead of waiting for the rm-hacks team to implement something.

**Comment by plan5** [comment]
> you will be putting yourself in a similar situation unfortunately, as rm-hacks does need to be updated with each release

That's a very good point. I'll close the issue because this clearly isn't a very sensible way to go about finding an alternative way to interact with the backend. I've thought about using inotifyd to parse file changes (e.g. renaming a notebook) and extracting commands from there. But that's for a different place than here.

> I personally would recommend helping get rm2fb working on newer versions, as that's something that you can work on right now instead of waiting for the rm-hacks team to implement something.

Agree. I hope I'll find my way into the topic (and the time). Am I right to assume https://github.com/timower/rM2-stuff is the place to be these days or is development still mainly happening in ddvk's repo?

**Comment by Eeems** [comment]
> > I personally would recommend helping get rm2fb working on newer versions, as that's something that you can work on right now instead of waiting for the rm-hacks team to implement something.
> 
> Agree. I hope I'll find my way into the topic (and the time). Am I right to assume https://github.com/timower/rM2-stuff is the place to be these days or is development still mainly happening in ddvk's repo?

That is a fork of rm2fb, as well as other project's of timower's. Ideally someone would figure out how to backport support for newer versions into the official rm2fb. So far nobody has done so.
