### ISSUE TITLE
Toolbar anomaly

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#247]
There's a black bar that appears above the toolbar toggle button when toolbar width is decreased.

- pen tool selected
- swipe down to hide toolbar
- swipe up to show quicktools
- swipe down to show toolbar

[Toolbar anomaly](https://github.com/knox-dawson/rm-hacks/assets/154367947/1e3a49d7-5b64-4d50-84de-10c2c9a49531)

**Comment by atngames** [comment]
I'll try to look into it. I was pretty sure I removed this bug earlier but... nevermind :D

**Comment by atngames** [comment]
I think this is fixed in the current alpha.

**Comment by atngames** [comment]
Closing as this is fixed in release 0.0.10
