### ISSUE TITLE
Lamy button with Highlighter

### ISSUE THREAD

**Issue by folofjc** [mb1986/rm-hacks#25]
I know that if the Lamy pen is far away, then clicking the button does not change the tool. You have to be close.

What I have noticed as well, is that if I am using the highlighter, and start pressing the button when it is farther away from the tablet (about 5-10cm), then it does not register the button press most of the time, and keeps writing with the highlighter.

I tried with a couple other pens, and it seems to not happen on them (pencil, fine liner, etc). Is there something "different" about the highlighter such that the button pressing code doesn't work as expected?

Thanks!

**Comment by mb1986** [comment]
It seems to be rM issue, even switching to/from highlighter by tapping seems to take longer. I wonder if it is related to the UI implementation - it has to replace the view for the highlighter parameters (possibly also when it is not visible). I'll take a look into that but not a priority for now. Are you fine with that?

Nonetheless, thanks for raising it!

**Comment by mb1986** [comment]
I've recorded two short videos in 240 FPS showing that: https://www.youtube.com/@rMHacks-kn5oe/playlists

**Comment by folofjc** [comment]
> . Are you fine with that?

Fine with  me! Not a pressing issue, just wanted to let you know.

**Comment by mb1986** [comment]
@folofjc, could you please check v0.0.6 pre-release?
I think I've improved it significantly.

```shell
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.6
```

**Comment by folofjc** [comment]
@mb1986 I tried it on the official 0.0.6 release and it looks like it works great to me! Thanks!
