### ISSUE TITLE
Post the source code

### ISSUE THREAD

**Issue by dafxy** [mb1986/rm-hacks#253]
In the spirit of open source, what about posting the source code of the patches so that people can contribute to the dev?

**Comment by Eeems** [comment]
Duplicates #3

**Comment by atngames** [comment]
Thank you for your interest in this project.
The link @Eeems wrote above has our answer to this issue. We would love to open source our code but unfortunately, we can't. You are welcome on our discord server and to show up on the monthly meetings we organize to gather people there.

**Comment by dafxy** [comment]
I am interested.

**Comment by atngames** [comment]
I am closing this issue.
Please refer to the duplicate issue pointed by @Eeems for further discussion
