### ISSUE TITLE
Bug - Uninstall hack

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#256]
I have uninstalled the hacks and can still use the experimental features:

1. 3-finger swipe down gesture to refresh the view
2. 5-finger gesture to refresh the screen
3. Swipe gesture to close and open the panel
4. taking screenshots

**Comment by mb1986** [comment]
I've made a mistake using rM experimental switches to turn on/off features.
I think the only solution would be to remove `[Experimental]` section form `/home/root/.config/remarkable/xochitl.conf`.

**Comment by PepikVaio** [comment]
You mean delete the whole paragraph?
So it's the original?

Now I've tried disabling everything and I still have the ability to take a screenshot of the screen.

**Comment by PepikVaio** [comment]
Fixed in version 0.0.10
