### ISSUE TITLE
Feature request && Big big thanks

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#26]
Hi I am very happy for this repo.
You are amazing.

My big problem is solved (exit button).
I am left hand user.

Very thank you for this amazing hack.
Please do you can implement this requests?

- [x] Table of content button - add to reMarkable panel.
- [ ] Back and forward in pdf files.
- [ ] Keep tags - When i press the button with pages and then I press some tag then i see only pages with tag. When I press the button with pages again I see all pages. 
- [ ] New layout for keyboard (cs, sk?????) - Thank you very much for this if possible.

Thank you for everything.

**Comment by mb1986** [comment]
Hi @PepikVaio, thank you for the kind words, it is very motivating :heart: I'll look what I could do :)

**Comment by PepikVaio** [comment]
V 0.0.7
Done - Table of content button - add to reMarkable panel.

**Comment by mb1986** [comment]
> New layout for keyboard (cs, sk?????) - Thank you very much for this if possible.

It should be possible in some time but I'd need a keyboard layout for these locales from you.

There are three rows with 10, 9 and 9 columns (letters). Could you please provide me what letters should be there for cs_CZ and sk_SK? Also what special characters should be there?

**Comment by Jayy001** [comment]
Closing this in preference of each feature request having it's own issue.
