### ISSUE TITLE
Support for v3.9.5.2026

### ISSUE THREAD

**Issue by mhantsch** [mb1986/rm-hacks#260]
Just got another update for my reMarkable 2. Had forgotten to turn off automatic updates previously...

`No suitable patch found for 'bbedc96941891a348dfcb3177495428aaf7e09a2'...`

**Comment by Slicc98** [comment]
Forgot to put mine into airplane mode and as I was getting ready, it updated. Sh*t

**Comment by rmelendezz** [comment]
I am in the same boat :/

**Comment by RedTartan04** [comment]
Just downgrade using [codextl](https://github.com/Jayy001/codexctl).
Either with the provided binary or if you have python installed it's `python codexctl.py install 3.9.4.2018`. Takes only seconds.

**Comment by rmelendezz** [comment]
> Just downgrade using [codextl](https://github.com/Jayy001/codexctl). Either with the provided binary or if you have python installed it's `python codexctl.py install 3.9.4.2018`. Takes only seconds.

Thanks a lot, going to try this out tonight.

**Comment by mb1986** [comment]
The port of the hacks 0.0.9 has already been prepared for 3.9.5.2026 for testing:

```sh
bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.1
``` 

It will be officially released soon :)

**Comment by NikosAlexandris** [comment]
> Just downgrade using [codextl](https://github.com/Jayy001/codexctl). Either with the provided binary or if you have python installed it's `python codexctl.py install 3.9.4.2018`. Takes only seconds.

Thank you. I tried to downgrade via `python codexctl.py restore` but despite the non-erroneous process (i.e. no error reported, seems to have worked), the version is the same (the last one, after the latest automatic upgrade). I guess it's something to ask over at https://github.com/Jayy001/codexctl. By the way, the official 3.10 is faster and more responsive, it feels.
