### ISSUE TITLE
Panel width - layers

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#265]
Bug - info in the video

https://github.com/mb1986/rm-hacks/assets/36114753/19a8e497-8387-4401-9720-8f5997782806

**Comment by atngames** [comment]
Hi, I thing I corrected it in the latest splitDoc iteration (non released).

This means it will be corrected in one of the next alpha releases for 0.0.10

**Comment by atngames** [comment]
Closing as this is fixed in release 0.0.10
