### ISSUE TITLE
Reset Viewport not working in landscape mode

### ISSUE THREAD

**Issue by ingatellent** [mb1986/rm-hacks#266]
When I open a document with the rm1 in landscape mode it correctly opens with page-width zoom aligned at the top.
If I then scroll down with three fingers it scrolls down such that I can see roughly 1/3 of the screen outside the document.

This used to work, the gesture would reset the viewport to page-width zoom aligned at the top, so I suspect it is an error introduced in 10 v2-4 or gestures-actions-maping

RM1
gestures-actions-maping
![Screenshot 2024-02-26 08_07_01 - page 1](https://github.com/mb1986/rm-hacks/assets/750082/e46c3165-0b96-413c-b94d-c69a16fddfb8)

**Comment by atngames** [comment]
I can not replicate this on my rm2 with 0.0.10 alpha4
Could you try to uninstall
```
bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ uninstall
```

**Comment by ingatellent** [comment]
I can confirm, that it indeed works on 0.0.10-alpha.4, but **not** on the patch gestures-actions-maping on my RM1.

**Comment by mb1986** [comment]
Could you please verify again after reinstalling again on 3.9.5.2026:

```sh
bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ uninstall
```
```sh
bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch gestures-actions-mapping
```

**Comment by ingatellent** [comment]
Unfortunately I get the same result on 3.9.5.2026 with the gestures-actions-mapping (which identifies itself as rM Hacks v0.0.10 in General Settings > Software)

Invoking the three finger swipe down, which is mapped to reset viewport resets the zoom level to 1.0 but also scrolls down, such that there is empty space above the document.

**Comment by ingatellent** [comment]
Reset viewport works fine in 0.0.10-alpha.5 on the same device.
