### ISSUE TITLE
KOreader Support

### ISSUE THREAD

**Issue by strasbourgeois** [mb1986/rm-hacks#271]
Hi,

Would it be possible to add KOreader support?

Previously it was possible to install KOreader to reMarkable with [this](https://github.com/ddvk/remarkable-autoinstall/tree/master/rm2) after installing ddvk rm hacks. But it does not support 3.x reMarkable updates any longer.

It would be really great to be able to use KOreader in reMarkable tablet.

Thanks

**Comment by Eeems** [comment]
rm-hacks is unrelated to supporting other third party software.  Same with ddvk-hacks. What you linked is an installation script for various tools. It would probably be better to follow the work being done to get toltec updated to support 3.x, which allows you to install KOReader and other applications.

**Comment by strasbourgeois** [comment]
I see. Thx for the precision. Is there any way to install KOreader to a reMarkable device with the 3.X updates installed?

Thanks

**Comment by Eeems** [comment]
> I see. Thx for the precision. Is there any way to install KOreader to a reMarkable device with the 3.X updates installed?
> 
> Thanks

The correct place to get information on how to install KOReader manually would be the KOReader wiki, not an unrelated project.

**Comment by atngames** [comment]
Thanks @Eeems 
@strasbourgeois this is outside of our scope here. I'd have a look here : https://github.com/koreader/koreader/issues?q=is%3Aissue+is%3Aopen+remarkable
I am closing this issue
atn
