### ISSUE TITLE
Have a wiki feature comparison for people wanting to migrate from 2.X to 3.X

### ISSUE THREAD

**Issue by builder-main** [mb1986/rm-hacks#272]
Hello started this and thought it could be quite interesting to have.

https://github.com/mb1986/rm-hacks/wiki/Comparison-Chart-with-ddvk-hacks

For now I only listed the Readme files features but I believe there are missing ones, such a pen gestures / sizes etc ...

And just as a kudos, QuickTools looks awesome !

**Comment by knox-dawson** [comment]
Added to wiki home https://github.com/mb1986/rm-hacks/wiki

**Comment by atngames** [comment]
It is empty right now, right ?

**Comment by builder-main** [comment]
Sorry pretty busy atm, I hope setting it up will still help to see what is on part and what is different.
