### ISSUE TITLE
Split Doc toolbar swipe and bookmark toggle issues (0.0.10-alpha.5 3.9.5.2026)

### ISSUE THREAD

**Issue by RedTartan04** [mb1986/rm-hacks#274]
1. Noticed that for a horz. split you can hide the toolbar with a swipe left to edge but can't show it again with swipe right from edge (that only works when done in the main doc).

2. In the split doc you can toggle the bookmark icon in the top right corner but it has no effect, i.e. it wont toggle an actual bookmark.

**Comment by atngames** [comment]
I fixed it, this will be okay in the next alpha (7)

I decided for now to hide the bookmark icon completely in the split doc. We will probably work on a bookmark ui for split document at some point but... later ;)

**Comment by atngames** [comment]
This was long ago. Hopefully this is fixed in current alpha (right ?)

**Comment by RedTartan04** [comment]
Sorry can't test as I'm still on 3.9.5 and a bit reluctant to update to 3.11 :-(

**Comment by PepikVaio** [comment]
Trying 0.0.10-alpha.10
There is no gesture option to hide the panel to the left - so I can't try it.

**Comment by atngames** [comment]
For right handed people, yes there is. Oh for left handed people, I tested and this feature does not exist!
Is there already an issue with such a request? Otherwise feel free to create one!

**Comment by atngames** [comment]
Otherwise, I can confirm that this issue is fixed in the current alpha.

**Comment by PepikVaio** [comment]
I am filing a complaint that there is discrimination against left-handers :).

Confirmed - corrected in beta.
