### ISSUE TITLE
SplitDoc (0.0.10-alpha.5) rm1 buttons and stylus hacks does not work

### ISSUE THREAD

**Issue by ingatellent** [mb1986/rm-hacks#279]
On RM1 the buttons does not work when in split doc mode: Neither the middle button which should either exit the document (or the splitdoc view), nor the page turning buttons, which I would expect to change pages in the main doc.

The stylus hacks does not work in the split doc-document (e.g. click button to undo or press and hold to erase) - the rubber button eraser works fine.

**Comment by ingatellent** [comment]
Correction: The rubber eraser seams to work fine most of the time only: And even when I open a notebook (not a .pdf) as a split doc the rubber eraser works in the split doc (which it still doesn't do https://github.com/mb1986/rm-hacks/issues/46).

However I encounter a few glitches, for example when I markup in the main doc, the writing also shows up in the split doc (but do not disappear when removed/erased).

**Comment by atngames** [comment]
This last glitch is when using the highlighter tool, right ?

As for the rm1 buttons, we'll have a look.

**Comment by ingatellent** [comment]
No, this is when using the fineliner tool and having split doc as a floating window.

**Comment by atngames** [comment]
Hi, I have the jumbo norris staedler and it works fine on the dev environment.
This means the eraser and double writing bugs should be fixed in alpha 6

There is still the  stylus button bugs. We will focus on this one pretty soon
