### ISSUE TITLE
Screen Refresh document toggle not showing in 0.0.10-alpha.5

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#285]
This option showed in 0.0.10-alpha.4, but I'm not seeing it in 0.0.10-alpha.5.

![image](https://github.com/mb1986/rm-hacks/assets/154367947/1cd228e2-84d4-463d-8478-bb1f2d63f515)

**Comment by atngames** [comment]
Hi,
I can see it on our development version.
You will have to wait for the alpha 6 ;)

**Comment by atngames** [comment]
Closing as this is fixed in release 0.0.10
