### ISSUE TITLE
Version fit 3.10

### ISSUE THREAD

**Issue by der-lu** [mb1986/rm-hacks#286]
Hey there,

Will there be a Version got the 3.10 Update?

Greetings
E

**Comment by RedTartan04** [comment]
Is 3.10 out of beta yet?

**Comment by der-lu** [comment]
No. Still in beta

**Comment by RedTartan04** [comment]
rm-hacks do not support beta version

**Comment by der-lu** [comment]
Shit. So hooefukly it gets out of beta soon. Using the cloud for the files is amazing. But rm-hacks ist so needful. Cant work without it

**Comment by atngames** [comment]
Hi,
Thanks for the kind words !
See you on next release ;)
