### ISSUE TITLE
PDF gets cut off when panning

### ISSUE THREAD

**Issue by KnutSolvig** [mb1986/rm-hacks#289]
Video posted on Discord channel. On 0.0.10 Alpha v.5.

**Comment by atngames** [comment]
As discussed on discord, we'll wait for a way to reproduce it
Thanks for the report

**Comment by atngames** [comment]
Okay, this one has been solved (and tested on a specific feature branch)

It should be included in the upcoming alpha (7)

Cheers

**Comment by atngames** [comment]
Can you confirm that is is fixed in 0.0.10 alpha.9 for rm's 3.11?
