### ISSUE TITLE
(Question) What’s gestures-action-mapping?

### ISSUE THREAD

**Issue by Kelvin88** [mb1986/rm-hacks#290]
What’s gestures-action-mapping feature listed under patches? Can’t find this feature in 0.0.10-alpha 6 settings.

**Comment by RedTartan04** [comment]
It's a parallel development branch. Another cool feature :) where you can assign actions to gestures. You can try it out (uninstall, then install that patch) but as the alpha it's not ready yet.

**Comment by Kelvin88** [comment]
Had impression it’s implemented in 0.0.10 alpha 6. Sounds very interesting.
