### ISSUE TITLE
(Question) What is Split Doc?

### ISSUE THREAD

**Issue by tempel33** [mb1986/rm-hacks#293]
I see quite a few people describing some issues with Split Doc.
I feel horribly silly but I cannot figure out how to open a document (2 documents?) in Split Doc.
All I could find by googling was that Remarkable cannot have a split screen.
Would anyone be willing to explain, or offer a link that explains Split Doc?
I am sorry if this something absolutely trivial...

**Comment by RedTartan04** [comment]
google wouldn't tell you what's going on in this github project 😂
The feature is still in alpha stage https://github.com/mb1986/rm-hacks/commit/25360fadc9f94661a842ca9703a0062ff530b642
Great things ahead. The developers are ace :-)
