### ISSUE TITLE
Bottom bar - copy and undo in PDF

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#299]
I've seen comments on adjusting copy and paste offsets for left-handed users.

Something must be wrong.
I'm posting a couple of pictures demonstrating the problem.
Sometimes the bar is unfinished.
Sometimes there is an invisible back button in the PDF document.
I hope this is understandable.

![image](https://github.com/mb1986/rm-hacks/assets/36114753/6bf9e5b8-9800-442b-beaf-a5366b1db90e)

![image](https://github.com/mb1986/rm-hacks/assets/36114753/7fe8ca3b-1b6c-4791-b6f9-ba3f26ad8041)

![image](https://github.com/mb1986/rm-hacks/assets/36114753/12797a68-3030-480d-835e-9cd12a450bf5)

![image](https://github.com/mb1986/rm-hacks/assets/36114753/78f47418-8671-487b-b8f2-03eeb3406298)

![image](https://github.com/mb1986/rm-hacks/assets/36114753/f3187bdf-2c10-4d52-bf65-5e3358755bcc)

![image](https://github.com/mb1986/rm-hacks/assets/36114753/5f3fb4b4-0be0-4ae7-bfb4-eb0e2faddf55)

**Comment by atngames** [comment]
Yes this needs fixing

**Comment by atngames** [comment]
Fixed in alpha 9 !

**Comment by PepikVaio** [comment]
I do not agree. 
I sent pictures on Discort.

**Comment by atngames** [comment]
Yeah I saw those and a last fix is currently being reviewed. So... Fixed in alpha 10 😅

**Comment by atngames** [comment]
Closing as this is fixed in release 0.0.10
