### ISSUE TITLE
0.0.9 working with 3.10

### ISSUE THREAD

**Issue by der-lu** [mb1986/rm-hacks#300]
It seems that 3.10 is out of beta. Does the actual stable Version works with it?

**Comment by Eeems** [comment]
If it's not on the compatibility table, it doesn't work with it yet.

**Comment by atngames** [comment]
We are probably going to try to update this week end.

**Comment by knox-dawson** [comment]
Mentioned this in discord, too.  Please let 0.0.10 also work with 3.9.5.2026, too.

**Comment by StarNumber12046** [comment]
> Mentioned this in discord, too. Please let 0.0.10 work with 3.9.5.2026, too.

latest versions require 3.9.5

**Comment by knox-dawson** [comment]
> Mentioned this in discord, too. Please let 0.0.10 work with 3.9.5.2026, too.

mb explained that, e.g., if alpha.7 is released for 3.10, then that's that.  Then when 0.0.10 is fully released (for 3.10), they can, if people want, make 0.0.10 work for 3.9.5, too.

I'm fine with that.

**Comment by mb1986** [comment]
Sure, 0.0.9 for 3.10.2.2063 is in the alpha stage with one known issue: not working ...zzZ.
