### ISSUE TITLE
Incorrect placement of “Clipboard clear” prompt in 0.0.10-alpha.6

### ISSUE THREAD

**Issue by FouzR** [mb1986/rm-hacks#304]
![IMG_7584](https://github.com/mb1986/rm-hacks/assets/88454554/bfb110c0-7fe4-400f-9921-9847689b6aea)

here’s a screenshot of the issue

**Comment by FouzR** [comment]
Seems like it was already mentioned in a different issue, my bad =P

**Comment by atngames** [comment]
Np
