### ISSUE TITLE
Random black dot at the top of the screen(persistent)

### ISSUE THREAD

**Issue by FouzR** [mb1986/rm-hacks#305]
![IMG_7585](https://github.com/mb1986/rm-hacks/assets/88454554/931f038d-6e09-4b46-a80b-be158828e8d0)

A persistent black dot appears randomly on the screen(usually after using split doc) and remains until I restart(0.0.10-alpha.6)

**Comment by FouzR** [comment]
Seems like it shows up specifically when you close a doc after using PiP split view. Not present in all other views, and switching views removes it

**Comment by atngames** [comment]
Wow nice catch!
What is PiP ?

**Comment by FouzR** [comment]
Picture in Picture, the smaller preview view

**Comment by PepikVaio** [comment]
I can confirm, it happened to me too. 
I didn't know what it was, after a reboot it disappeared.

**Comment by atngames** [comment]
Okay, this is fixed and waiting for approval.
Just have to wait for a bit ;)

**Comment by atngames** [comment]
It is now fixed in alpha.9, right ?
