### ISSUE TITLE
0.0.10 installation uninstallation 

### ISSUE THREAD

**Issue by radar3d** [mb1986/rm-hacks#312]
When I paste the installation line it just installs ver. 0.0.9. Also when I try the _uninstall line it doesn’t uninstall.

bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.10-alpha.7

bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ uninstall

**Comment by radar3d** [comment]
I’ve got to wait for a version 3.12 patch to be available before I can try again.If I understand correctly you have to have a patch that has been checked to upgrade what you currently have.Raymond Luck 🇺🇸On May 29, 2024, at 6:01 PM, atn ***@***.***> wrote:﻿
Weird.
Do you still have this issue (update has changed a bit recently) ?
Did you try with the latest alpha ?
What is your tablet's version ?
Thanx for reporting

**Comment by atngames** [comment]
Yes each rmhacks version is for a specific remarkable version. Sorry about that

**Comment by radar3d** [comment]
No no I completely understand.  That’s why I’m waiting just didn’t want to be dumb if you had a way to avoid it…Any idea when the patch for version 3.12 will be out?Thank you for the prompt reply.Raymond Luck 🇺🇸On May 30, 2024, at 11:43 AM, atn ***@***.***> wrote:﻿
Yes each rmhacks version is for a specific remarkable version. Sorry about that

**Comment by PepikVaio** [comment]
When 3.12 is official and not a beta. 
rm-hacks is not for betas.

**Comment by radar3d** [comment]
Copy that, makes sense.  That’s why I turned off my auto update and beta the other day to wait for em-hacks to get there.  When I leave it on I’m always a version or two ahead :-(Raymond Luck 🇺🇸On May 30, 2024, at 12:20 PM, Wajsar Josef ***@***.***> wrote:﻿
When 3.12 is official and not a beta.
rm-hacks is not for betas.
