### ISSUE TITLE
Orientation button in document gone

### ISSUE THREAD

**Issue by zutesuit** [mb1986/rm-hacks#316]
Have installed the alpha for 0.10 and the option to change orientation inside the document is gone for me.

**Comment by evando1189** [comment]
check the General Settings area in your rM Hacks Configuration. The 4th option from the top is new and now defines whether the screen orientation can be set in each document or if it defaults to whatever is selected as your main orientation (what your My Files is set to). Turn this setting off to have document level control again.

**Comment by zutesuit** [comment]
Ahhh, I'm so sorry, I thought I'd looked thoroughly, must have missed it. I
apologise and thank you.

**Comment by atngames** [comment]
Thanks for this quick fix :D
