### ISSUE TITLE
Feature request: Add toolbar for additional pen

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#32]
- [ ] Another pen selection panel.

Is it possible to add another pen selection panel?
I would often use it this way.
For example, one for the pen and one for the highlighter.

Thank you very much for this feature.

**Comment by atngames** [comment]
I think quick tools definitely solved this issue so I am closing it.
Thanks for bringing this up!

**Comment by PepikVaio** [comment]
Maybe I misspoke.
I would like to add another pen to the original panel.
To have all the features that the original side panel has.
The quick tool doesn't have all the options yet.

**Comment by atngames** [comment]
To be clear, you would need a second tool icon in the left panel ?

**Comment by PepikVaio** [comment]
Like this

![Screenshot 2024-06-03 18_24_59 - page 1](https://github.com/mb1986/rm-hacks/assets/36114753/f3ae53ae-88b7-496f-9b64-d842eace7480)

**Comment by PepikVaio** [comment]
From what I've read, it will be in the next update of the official version - closing.
