### ISSUE TITLE
Version request 3.11

### ISSUE THREAD

**Issue by nelly-ferrule** [mb1986/rm-hacks#322]
Requesting an update for 3.11. 

New here so hope this request is the right way to go about it!

**Comment by pragmatically-dev** [comment]
Would be nice but the main problem is that the version 3.11 isn’t out of beta (yet).  when you roll on the beta program you agree not to install any third party software hehe

**Comment by Eeems** [comment]
https://github.com/mb1986/rm-hacks/issues/67#issuecomment-1837635619

**Comment by nelly-ferrule** [comment]
Thanks, no worries! 
I had unsubscribed from the beta program and did a factory reset, hoping it would return to 3.10, but nope. I will just have to be patient I guess!

**Comment by Eeems** [comment]
> Thanks, no worries! I had unsubscribed from the beta program and did a factory reset, hoping it would return to 3.10, but nope. I will just have to be patient I guess!

I would usually link to you https://remarkable.guide/faqs.html#can-i-downgrade-to-a-different-os-version, but it looks like 3.11 has done a large change to how upgrades are handled. You could try just switching your active partition to the previous version you had installed, and then installing 3.10.

**Comment by nelly-ferrule** [comment]
Thanks. I've been looking at some instructions and don't feel confident that I mightn't end up bricking it, so I think I'll wait it out.

**Comment by RedTartan04** [comment]
> it looks like 3.11 has done a large change to how upgrades are handled. 

😱 More info on that anywhere?

**Comment by Eeems** [comment]
> > it looks like 3.11 has done a large change to how upgrades are handled. 
> 
> 😱 More info on that anywhere?

The community discord has some more information in the beta channel.

**Comment by beelux** [comment]
There's an alpha out for 3.11.2.5.

**Comment by beelux** [comment]
05b14c25dc67d732e896c4580070f23c59aca780 added full support for 3.11.
