### ISSUE TITLE
How Do I install the alpha? 

### ISSUE THREAD

**Issue by der-lu** [mb1986/rm-hacks#327]
Please can someone Tell me how to install the latest 0.0.10 alpha?

And für security, how to uninstall it?

Thanks in advanced and sorry for the maybe "stupid" question.

**Comment by PepikVaio** [comment]
Join Discord, there are links.

**Comment by der-lu** [comment]
Ok. So I will try discord. Can you Post the Channel link?

**Comment by Eeems** [comment]
> Ok. So I will try discord. Can you Post the Channel link?

It's in the readme.

**Comment by zelomel** [comment]
You can also find the installation procedure in the Wiki : https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation-0.0.10

**Comment by beelux** [comment]
As others said, the README.md contains uninstallation instructions.

The alphas are announced on the Discord, with their corresponding fw version.
While you could likely infer some alpha information from the commits, I'd still recommend checking the Discord, as it also includes other users talking about their experience with the alpha. (and how well it works/how broken is it)
