### ISSUE TITLE
Feature Request - toggles panel like ddvk

### ISSUE THREAD

**Issue by Tridens92** [mb1986/rm-hacks#33]
I LOVE ddvk's toggle panel.,  The ability to toggle things on and off is such a help. The ones I use most often are:

- Wifi
- rM1 Buttons
- Swipes

Thanks for considering this, and your great work!

**Comment by PepikVaio** [comment]
Turn multiple pen thicknesses on and off in main settings.

**Comment by Tridens92** [comment]
Thanks for adding these!  Here's the others I use most often:

1) Swipes OFF/ON 
2) rM1 Buttons OFF/ON (wasn't sure if your comment re: rM1 buttons in v0.0.6 was this toggle functionality or something else, like toggle eraser (ddvk hack feature)?

Thanks again for your work!

**Comment by mb1986** [comment]
Thanks for kind words!
Would you like to save the Swipes / rM1 Buttons toggle states between different documents opens or even device restarts?

**Comment by Tridens92** [comment]
`Would you like to save the Swipes / rM1 Buttons toggle states between different documents opens or even device restarts?`

I think saving the toggle states for both swipes and rM1 buttons between different documents is a good idea (this is the way ddvk works).  Re: device restarts, it would seem better to me for the device to return to a "default" state (swipes and buttons both activated).

`Second question, would you like to disable all swipes or introduced by hacks only?`

I would say definitely disable all swipes.  It's too easy to accidentally change pages while writing.

Thanks again...can't wait to give these new features a try!
