### ISSUE TITLE
RM1 and LAMY to 3.x version

### ISSUE THREAD

**Issue by coolajami** [mb1986/rm-hacks#332]
Hi, apologies if that was asked before or if it was mentioned somewhere, but I couldn't find a clear answer on this. I'm using a RM1 with the DDVK hack for the LAMY pen (yes,I'm still on version 2.x) and I'm looking to update to version 3.x and I was hoping somebody be kind enough to confirm or not if the hack is still working for the RM1. 
Thank you in advance.

**Comment by ZacharieALES** [comment]
Yes it works. I think you are asked at the installation if you additionally want to add the lamy hack.

**Comment by coolajami** [comment]
> Yes it works. I think you are asked at the installation if you additionally want to add the lamy hack. 

great, thank you. I'll make a leap of faith and I will install it today.

**Comment by beelux** [comment]
mb1986 started this whole project the intent of getting the LAMY pen to work again on his rm1, so yes! 😁

Note that currently only 3.10 is supported and 3.11 is in alpha.
