### ISSUE TITLE
Extracting and moving PDF pages between files enhancement

### ISSUE THREAD

**Issue by evando1189** [mb1986/rm-hacks#334]
It's already possible to do the following via the rM firmware and these rm hacks:
1) for a native rM notebook or quick sheets, we can extract/"Move out" a page and put it into a different native rM notebook or quick sheets, or into a PDF file,
2) duplicate a PDF page inside of a PDF file to create a new identical PDF page, and this keeps all embedded URLs intact so that they still take you to the correct pages inside the same PDF file,
3) create a new blank native rM page directly from inside of a PDF file. 

My idea for an enhancement is to make it possible to extract/"Move out" a page from a PDF file and be able to move it into a different PDF file or into a native rM notebook/quick sheets. 

Since the above functions are already possible, hopefully this wouldn't be too terribly difficult to implement, but I don't know the code, so I have no idea.

**Comment by knox-dawson** [comment]
Probably duplicates https://github.com/mb1986/rm-hacks/issues/173

**Comment by evando1189** [comment]
yes you're correct, didn't see that one.
