### ISSUE TITLE
Quicktools swipe to hide intermittently changes pen instead

### ISSUE THREAD

**Issue by Tridens92** [mb1986/rm-hacks#335]
I'm having intermittent results trying to swipe up on the Quicktools toolbar to hide it.  Sometimes it works, but more often it just changes which of the pens in the Quicktools menu is selected (and sometimes chooses the eraser as well, which isn't in my Quicktools bar).

If it makes any difference, I have the Quicktools bar set to Horizontal format.  Thanks for any help!

**Comment by Tridens92** [comment]
Update on further testing -- the swipe up feature works reliably if the the option "QuickTools as header" is enabled/on.  If it's off, the problem I report above happens.

**Comment by knox-dawson** [comment]
Sounds like you may be swiping too close to the upper left corner.  If you don't need it, you could toggle off the gesture to swap last tool with eraser.  Unless I'm missing something.

**Comment by atngames** [comment]
@Tridens92 can you confirm @knox-dawson 's insight ?

**Comment by Tridens92** [comment]
Sorry for delay!  Yes, I can confirm that this works.  Is there a graphic representation of where the swipe zones are for this hack?  I would never have assumed I should be swiping further away from the corner.

Thanks @knox-dawson for the insight!

**Comment by atngames** [comment]
Cool, I am closing this issue. 

Yes we might work on a visual cheat sheet for zones soon. 
Thanks for your help
