### ISSUE TITLE
Feature request: writing closer to the "current tool" icon

### ISSUE THREAD

**Issue by mrwth** [mb1986/rm-hacks#337]
Currently one cannot start a stroke close to the "current tool" icon (when the toolbar is closed), see the screenshot. Would it be possible to decrease this "forbidden area"?
![image](https://github.com/mb1986/rm-hacks/assets/16231246/bf2c134e-2a4b-497d-8aa7-5eb26658dd46)

**Comment by PepikVaio** [comment]
Duplicate: #224

**Comment by beelux** [comment]
@PepikVaio Isn't your issue about the inconsistency of what's visible, meanwhile this issue about not being able to start writing within that area?

**Comment by atngames** [comment]
This would be possible, but would mean a smaller button and so difficulty to open the toolbar.
Not sure it is a good idea

**Comment by mrwth** [comment]
@atngames the area which works as a button is smaller than the area where one cannot start a stroke; I would like to shrink that larger area and to make it coincidence with the smaller one (which would stay as it is now)

**Comment by atngames** [comment]
I think I am going to work on #336 and this would be less needed, right? One stone, two birds... 🤗

**Comment by atngames** [comment]
I did actually work on this.
Could you confirm that it is fixed now ?

**Comment by PepikVaio** [comment]
Fixed in version 0.010
