### ISSUE TITLE
feature request: support for transparent sleeping page

### ISSUE THREAD

**Issue by andreapanontin** [mb1986/rm-hacks#340]
It's possible to change the displayed sleeping/suspended/etc screen of the device (they are located in /usr/share/remarkable). You can easily find guides online.
ddvk's hacks supported the following feature: if you replaced any of those screens with a png with some transparent areas, when invoking that screen it would just superimpose the png on the content that was shown on the page, which could still be seen through the transparent areas. Right now the transparent parts are rendered white.

For example, when viewing a pdf or some notes, I could use a sleeping page with a black bar over the toolbar and all the rest being transparent. In this way, when putting the remarkable to sleep, I was able to still read the text of the document, while being unable to interact with it (sometimes it's desirable to me).

I hope my description is understandable :)
If it is implementable it would be very nice to have :)

(also, in the meantime, a huge thanks for this project: it fills a huge gap that was left with the switch to v3, it's really appreciated!)

**Comment by RedTartan04** [comment]
This was possible in earlier 2.x version and had sparked a lot of creative, partially transparent sleep images. But the company removed this. I'd like to have it back, too (though low priority).

**Comment by PepikVaio** [comment]
The feature you're talking about is back. 
Did I misunderstand?

![image](https://github.com/mb1986/rm-hacks/assets/36114753/591983f5-a6fb-454a-8903-11d228798c93)

**Comment by andreapanontin** [comment]
It is a slightly different feature. The main difference is that I can't trigger the light sleep mode by pressing the power button.
What I am looking for is essentially the ability to trigger light sleep when I want to, without having to wait 20' without touching the tablet (and also with the possibility of placing the banner telling me that the tablet is sleeping in a different position)

**Comment by PepikVaio** [comment]
Okay, I get it. You mean this?

**Comment by RedTartan04** [comment]
Umm, maybe we're talking about different things. What *I* meant was support for transparency in 'suspended.png', i.e. the (deep) sleep screen (see e.g. https://www.reddit.com/r/RemarkableTablet/comments/hj6tox/torn_paper_sleep_screen_using_a_partially/) This was possible befor rM v2.9 IMHO

This could be used for fun or to show the open doc's content, even in deep sleep wich is activated by button press.

Light sleep is a different state, has no associated png file and is supported and improved by rmhacks (showing the zzzZZZ).

**Comment by PepikVaio** [comment]
OK, I finally understand :)
That's news to me,I didn't even know the changes went. 

I guess it would be fun, but what @AndreaPanontin is asking for goes with rm-hacks just so he can't choose his image but has zzzZZZ. 
Yes, zzzZZZ is sometimes small and sometimes it takes me a while to realize that reMarkable is asleep :)

**Comment by andreapanontin** [comment]
Actually I was not aware of how internally lightsleep and (deep) sleep work completely differently. I am indeed asking for exactly what @RedTartan04 said, and I thank them for saying it better than I was able to :smile: 

At the same time I was not aware of the gesture to get into light sleep (thanks a lot for showing it to me @PepikVaio !), which is definitely _a lot_ better than nothing. But I got used to having a way bigger banner signaling that the device is asleep, for which this is not an exact replacement :)

(of course I understand the low priority of this request!)

**Comment by Eeems** [comment]
Adding transparency support to suspended.png is a feature that ddvk-hacks added back after it was removed, so it would be worth exploring implementing in rm-hacks in my opinion.

**Comment by atngames** [comment]
Hi, I quickly looked at it and it seems doable.

I'll add it to my to-do list

**Comment by atngames** [comment]
It seems to work! I'll try to clean it and make it a real thing during the week.

![Uploading IMG_20240528_222007.jpg…]()
