### ISSUE TITLE
Bottom bar

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#343]
Hi, I found another issue.

1. When i copy some object, bottom bar show me "Tap with Marker to paste | Clear clipboard" this is right.
2. When I click on link in PDF file, bottom bar show me "<- Back to page xx" or "Back to page xx->" this is right.

But, when I want both, It is not working.
When I have selected  lasso tool, I can not see "<- Back to page xx" or "Back to page xx ->"

Can you add "<- Back to page xx" or "Back to page xx ->" on bottom bar when is selected lasso tool?

![IMG_4971](https://github.com/mb1986/rm-hacks/assets/36114753/a23b2986-e2d5-4828-8cc2-b0118d9afcd5)
![IMG_4972](https://github.com/mb1986/rm-hacks/assets/36114753/91768c21-90e5-48bb-9049-98cc536cf146)

**Comment by atngames** [comment]
Oh this is probably a z-index issue (both bars are here but the wrong one is on top.
I'll have a look !

**Comment by PepikVaio** [comment]
Now I checked, the official version works just as bad :) 

So it is not a bug.
