### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by akademy** [mb1986/rm-hacks#345]
Hi,

I'm getting a 404 error when running the install command. 

    bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.10-alpha.10

output:

    reMarkable: ~/ bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.10-alpha.10
    Connecting to raw.githubusercontent.com (185.199.108.133:443)
    wget: note: TLS certificate validation not implemented
    writing to stdout
    -                    100% |************************************************************************************************************************************| 11136  0:00:00 ETA
    written to stdout
    
     rM Hacks Installer 
    --------------------
    
    Trying to download and install patch: '0.0.10-alpha.10'
    Connecting to raw.githubusercontent.com (185.199.110.133:443)
    wget: note: TLS certificate validation not implemented
    wget: server returned error: HTTP/1.1 404 Not Found
    error reading input file
    tar: invalid magic
    tar: short read

Has the name changed recently? (maybe the "alpha" dropped). I copied the command from here https://github.com/mb1986/rm-hacks/wiki/rM-Hacks-Documentation-0.0.10

**Comment by PepikVaio** [comment]
Use this code:
bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)"

0.0.10 is official out.

**Comment by akademy** [comment]
Thanks. Everything working nicely now!
