### ISSUE TITLE
Feature Request: Lamy button double-click for Undo

### ISSUE THREAD

**Issue by Tridens92** [mb1986/rm-hacks#35]
The title says it all.  :)  Thank you!

**Comment by mb1986** [comment]
Yeap, I've forgot about this one, will add it at some point in time ;)

**Comment by mb1986** [comment]
Will be delivered with #38, to test it run `sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.5` before PR is merged.
