### ISSUE TITLE
Upside down screenshot

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#359]
I'm in "Inverted Protrait" orientation.  I did a screenshot gesture with Import as PDF.  I look at the PDF and it is upside down.

Do I care? Not particularly.  I can easily just choose a different orientation.  I mention it in case you might consider it a bug.  If you don't, and you want to close this issue, that's okay with me.

**Comment by mb1986** [comment]
Unfortunately, I do not have any control over how screenshot is taken. Sorry.
