### ISSUE TITLE
Better location to toggle Eraser Selection

### ISSUE THREAD

**Issue by Kelvin88** [mb1986/rm-hacks#36]
Hi. Thank you for this hack!

Would like to suggest a better location instead of top left swipe up to toggle eraser selection. Most of the time while writing, it's difficult to go all the way up to exact corner to logger to eraser, can we have an option to replace toolbar toggle which is easier to access with eraser selection? Don't toggle toolbar as often as eraser selection. Thank you.

**Comment by mb1986** [comment]
Hi, thanks for the suggestion - yes, I think we could add that option. For now I'd like to focus on configuration storage and UI and just after that it will be easier to toggle different hacks and configure them.

**Comment by Kelvin88** [comment]
Thank you for agreeing. Look forward to implementation. Have a good weekend.

**Comment by rudy0ne** [comment]
Just wanna add that I would also love the option to move both tool-switching gestures to the top right corner, when the time comes. Thanks!

**Comment by rudy0ne** [comment]
This was solved for me by just switching to left-handed mode! And I'm actually right handed, but since the toolbar's so easy to hide with the gesture it'll never be in my way.
