### ISSUE TITLE
Support for v3.11.3.3

### ISSUE THREAD

**Issue by pichiste** [mb1986/rm-hacks#360]
Just got my first rM but it's already on v3.11.3.3 which isn't supported yet:
```
No suitable patch found for '3d14a435fbf23e79f43bfd90bf16d988009c38e9'...
```

I'll eagerly await :) Thanks for your work on this!

**Comment by patrickplaggenborg** [comment]
Same here. Updated from 2.x to 3.x to keep cloud syncing working, then saw it updated to 3.11.3.3 which is not supported yet.

Looking forward to rm-hacks becoming compatible with this one :-)

**Comment by ZacharieALES** [comment]
I had the same problem and I was able to roll back to the previous version using the following commands in ssh (obtained from [here](https://github.com/ddvk/remarkable-hacks/issues/287)):

`fw_setenv "bootcount" "0"

OLDPART=$(fw_printenv -n active_partition)
if [ $OLDPART  ==  "2" ]; then
    NEWPART="3"
else
    NEWPART="2"
fi
echo "new: ${NEWPART}"
echo "fallback: ${OLDPART}"

fw_setenv "fallback_partition" "${OLDPART}"
fw_setenv "active_partition" "${NEWPART}"
reboot`

**Comment by pichiste** [comment]
Just saw the release for this, thanks!
