### ISSUE TITLE
3.12.4.0 support

### ISSUE THREAD

**Issue by No1089** [mb1986/rm-hacks#363]
I was on the BETA line for Remarkable and it appears I cannot use rm-hacks as a result.
Digging into the install script it's apparent the patches are encrypted, and reliant on the local binary to decrypt - so there is no way to force a patch on a higher version - that's an assumption on my part.

Am I correct that the source required to modify the patch behaviour is not available anywhere?

**Comment by pragmatically-dev** [comment]
now it is stable :c  I just updated my device expecting 3.11.3 but got 3.12.4 :sob:

**Comment by pragmatically-dev** [comment]
F

**Comment by No1089** [comment]
Understood on the BETA distinction - but still fuzzy on how anyone is supposed to contribute to the effort if the code is simply a blob that's loaded by the installer?
What's the rationale for this approach?

**Comment by mb1986** [comment]
The rM code is proprietary, so we cannot share it publicly. However, you can contribute by testing, providing feedback, and requesting new features or ideas.
