### ISSUE TITLE
Can't get stylus hacks to install

### ISSUE THREAD

**Issue by alexnegron** [mb1986/rm-hacks#365]
Installing with the automagic command 

`bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)"
`

and responding "Y" to the question about installing the stylus hacks results in an error: 

> Would you like to install 'ddvk/remarkable-stylus' [Y/n]? Y
> Fetching secure wget...
> wget: note: TLS certificate validation not implemented
> wget: TLS error from peer (alert code 40): handshake failure
> wget: error getting response: Connection reset by peer
> \e[31mError: Could not fetch wget, make sure you have a stable Wi-Fi connection\e[0m

I have a secure wifi connection and could get the hacks installed when I respond with "n".

**Comment by Eeems** [comment]
What OS version is the device?

**Comment by Eeems** [comment]
I've just verified that the static wget that it's downloaded is being served over http and not https, and that it doesn't upgrade the request. Do you have anything on your network that might be changing requests in any way?

**Comment by Jayy001** [comment]
Closing as no response
