### ISSUE TITLE
Locked, Hidden, and Encrypted Folders

### ISSUE THREAD

**Issue by nathangur** [mb1986/rm-hacks#367]
I have owned my Remarkable 2 for over a year and a half now and have been unable to use it for work due to there being no way to securely store confidential data on device without having it upload to the cloud or be accessed easily using ssh. 

In the same vein as locked/encrypted folders is hiding folders. Either they would only be found in a certain section or would only appear in searches.

**Comment by PepikVaio** [comment]
You don't have to use the reMarkable cloud. 
Try using RCU or reMarkable fakecloud.

**Comment by nathangur** [comment]
> You don't have to use the reMarkable cloud. Try using RCU or reMarkable fakecloud.

I know and I do, those files are still not locked, hidden, or encrypted.

**Comment by PepikVaio** [comment]
Yes, you're right. 
You can still create a blank PDF that is locked and add pages to it directly in reMarkable.

**Comment by Jayy001** [comment]
This falls under #28. In terms of access via SSH, rmHacks can't do anything to prevent that - only via the UI.
