### ISSUE TITLE
Drawable Shapes

### ISSUE THREAD

**Issue by nathangur** [mb1986/rm-hacks#368]
I like to use my remarkable to write research papers and plan projects out. However my mortal enemy is drawing a circle. My suggestion is to have a list of shapes (circle, square[can become a rectangle by stretching], diamond, eclipse, parallelogram, etc) that can be adaptively drawn by pressing where you want one end of the shape to be and dragging to where you want the opposite end to be (similar how photoshop works).

**Comment by PepikVaio** [comment]
As far as I know, the shapes are being worked on. 
For now, try drawj2d:

https://sourceforge.net/p/drawj2d/wiki/reMarkable/

**Comment by knox-dawson** [comment]
Probably a duplicate: https://github.com/mb1986/rm-hacks/issues/328

**Comment by nathangur** [comment]
> Probably a duplicate: #328

A bit similar, my proposal is like how the straight lines in remarkable work. Where you hold down one end of the line and drag where you want the opposite end to be.

**Comment by knox-dawson** [comment]
> > Probably a duplicate: #328
> 
> A bit similar, my proposal is like how the straight lines in remarkable work. Where you hold down one end of the line and drag where you want the opposite end to be.

Yep, I agree.  In particular, as a shape changes size (in this hypothetical scenario), the widths of the lines in that shape should remain the same size you initially selected.

Currently, you can copy a pre-generated shape and resize it, but when you make it bigger or smaller, it also makes the thicknesses of the shape's lines thicker and thinner.

**Comment by FluffLescure** [comment]
Any updates for shapes? It's one the most and longest awaited feature

**Comment by Jayy001** [comment]
Going to put this under #328.
