### ISSUE TITLE
Gestures mapping ETA?

### ISSUE THREAD

**Issue by Kelvin88** [mb1986/rm-hacks#370]
Codes for gestures mapping was first tested about 5 months ago but there’s no news after. Any ETA when it will come out?

**Comment by StarNumber12046** [comment]
+1

**Comment by mb1986** [comment]
Yes, I miss them too :) Now, I'll focus on new versions support.

**Comment by Kelvin88** [comment]
Great! Wait patiently for gestures mapping.
