### ISSUE TITLE
Quick sheets issue

### ISSUE THREAD

**Issue by KimSo82** [mb1986/rm-hacks#371]
I'm having some issues with Quick sheets and I don't know if it's related to rM Hacks.

I have software version 3.11.2.5 with rM Hacks v0.0.10.

The problem is that when I delete a Quick sheet (it's on trash) and I create a new, it creates a new page on the Quick sheet that is on the trash.

If I empty the trash I can't create any new Quick sheet and when I try to click on the New Quick Sheets button it doesn't do anything.

I have another issue, when I create a new Quick sheet and rename it, once I want to create a new Quick sheet, it creates a new page on the Quick sheet that I have renamed.

My expectation is that If i create a new Quick sheet, once is renamed or deleted (in trash) it really creates a new one. And if I have emptied the trash, it let me create a new Quick sheet.

**Comment by knox-dawson** [comment]
I would be surprised if this is a rM Hacks problem.  You could verify that by uninstalling rM Hacks and see if the problem persists. I would check it out, but I don't want to fall into a trap.  :-)

**Comment by KimSo82** [comment]
Hi knox.

I have asked to reMarkable support and they answered this:

> Dylan: Could you please try updating the software version by tapping on Software and then tapping on Check for updates?

> Dylan: Just to let you know I was referring updating to the beta version as **this is a known issue that has been fixed in the beta version**.

So I will wait to the new software version and corresponding rM Hacks version to check if they have fixed the problem.

Thank you
