### ISSUE TITLE
Feature Request: Sort file list by file name not file metadata

### ISSUE THREAD

**Issue by niklasarnitz** [mb1986/rm-hacks#372]
I often use my remarkable to read ebooks, but their metadata is often broken.
I tend to name the ebook files [Author] - [Book Name] - [Edition].epub but the remarkable always ignores that sorting and extracts the metadata from the ebook.

It would be great if there would be an option to disable that metadata mechanism for PDF and EPUB files.

**Comment by PepikVaio** [comment]
It is a mistake to use the filename. 
Metadata is native the right way. 

It's not reMarkable's fault. 

Try fixing the metadata with calibre. 
Free on all platform (pc, mac, linux).

**Comment by mb1986** [comment]
I think that rM does not store the filenames (?). I may be wrong though.

**Comment by Jayy001** [comment]
rM doesn't seem to store the filename, so we wouldn't be able to add any hacks.
