### ISSUE TITLE
3.3.2.1666 support

### ISSUE THREAD

**Issue by donut-but-a-brain** [mb1986/rm-hacks#373]
I saw on the compatibility chart that one of the versions may be compatible with 3.3.2.1666. For the sake of Toltec 3.x users, what is the state of this compatibility? How likely is it to bootloop?

**Comment by mb1986** [comment]
It should be compatible, but it contains old version of hacks. You can test it if you want. Please tell me if it works or not :)

**Comment by Eeems** [comment]
@mb1986 it works
