### ISSUE TITLE
Add option for wider columns using rypefolio

### ISSUE THREAD

**Issue by millerville** [mb1986/rm-hacks#382]
Remarkable just added an option to toggle column with when typing in landscape mode.  Is this something you are working toward?

**Comment by PepikVaio** [comment]
Hi, where do you have the option to write in columns?
I have 3.14 and I can have narrow or wide column but only one- even if I have landscape mode.

**Comment by millerville** [comment]
New remarkable beta software has the option if you click on the text icon to have wide or narrow margins when typing. See imageRyanOn Jul 31, 2024, at 7:33 AM, Wajsar Josef ***@***.***> wrote:﻿
Hi, where do you have the option to write in columns?
I have 3.14 and I can have narrow or wide column but only one- even if I have landscape mode.

**Comment by millerville** [comment]
Does rmhacks let you type in wide column?RyanOn Jul 31, 2024, at 7:33 AM, Wajsar Josef ***@***.***> wrote:﻿
Hi, where do you have the option to write in columns?
I have 3.14 and I can have narrow or wide column but only one- even if I have landscape mode.

**Comment by PepikVaio** [comment]
Okay, I get it.
I also have the option of narrow or wide column.
I thought you could type in 2 columns side by side if you put reMakable to width.

In that case, I don't understand why this issue arose?

**Comment by millerville** [comment]
I dont think you can do wide/narrow with rmhacks can you?RyanOn Aug 6, 2024, at 12:39 PM, Wajsar Josef ***@***.***> wrote:﻿
Okay, I get it.
I also have the option of narrow or wide column.
I thought you could type in 2 columns side by side if you put reMakable to width.
In that case, I don't understand why this issue arose?

**Comment by PepikVaio** [comment]
You can't, but why would they add it to the rm-hacks if it's going to be in the official version?
It doesn't make sense.

Rm-hacks only add minor improvements to the official version.

So just wait until rm-hacks is updated to the version where this feature is.

**Comment by millerville** [comment]
Thanks. Agree.  RyanOn Aug 6, 2024, at 2:46 PM, Wajsar Josef ***@***.***> wrote:﻿
You can't, but why would they add it to the rm-hacks if it's going to be in the official version?
It doesn't make sense.
Rm-hacks only add minor improvements to the official version.
So just wait until rm-hacks is updated to the version where this feature is.

**Comment by PepikVaio** [comment]
I recommend closing this issue.
If your question is asked.
