### ISSUE TITLE
3.14.1.9 support 

### ISSUE THREAD

**Issue by alveitia** [mb1986/rm-hacks#388]
Is there a timeline for implementing rm-hacks to 3.14.1.9?

**Comment by Eeems** [comment]
Duplicates #385

**Comment by dylee** [comment]
It's been 3 months since the last commit on this repo. Is this project dead?

**Comment by kaleko** [comment]
Agreed with @dylee. Is this dead? I was forced to upgrade my RM2 to 3.14.1.9 to maintain cloud connectivity, and it's crap without rm-hacks. If rm-hacks is discontinued, I will just buy a RMPP instead.

**Comment by Alistair-Dublin** [comment]
I don't think these comments are helpful. The people who work on this provide a really valuable add-on and they do it for free. Remarkable just released a massive update and I would imagine this had a big impact on the codebase. The update will come when it comes, and it will be very much appreciated by the majority of users.

**Comment by kaleko** [comment]
@Alistair-Dublin My point in commenting is not to pester the authors or ask for predicted timelines etc, of course their contributions are invaluable and _super_ appreciated. Honestly rm-hacks is the only thing making my RM2 usable.

My purpose is just to get a signal that the authors even have an intention to continue developing this. For example, I could imagine them deprecating this entire code base and focusing on supporting the RM pro instead.

A simple "still working on this" comment from an author is all I'm hoping for :)

**Comment by Eeems** [comment]
There are monthly meetings you can take part in on the discord to find out the current status of things.

**Comment by dylee** [comment]
> There are monthly meetings you can take part in on the discord to find out the current status of things.

This is super helpful. Thank you. If you can paste in the discord URL I'd appreciate it greatly. I only asked whether the project is dead or not because I wanted to see whether I and a few others may take it on if it did die.

**Comment by Eeems** [comment]
The link is in the readme at the very top.

**Comment by jamespo** [comment]
Why do these comments always seem to be made by users with no contributions to anything?

**Comment by Eeems** [comment]
> Why do these comments always seem to be made by users with no contributions to anything?

Because this project is used by a lot of people who don't write software.

**Comment by jamespo** [comment]
> > Why do these comments always seem to be made by users with no contributions to anything?
> 
> Because this project is used by a lot of people who don't write software.

It's also used by a lot of people who do write software but don't seem to create issues.

**Comment by mb1986** [comment]
There is no timeline, we are doing hacks in our spare time and lately I had some important things to sort out first.

**Comment by alveitia** [comment]
Thanks for the reply, I'm rooting for you guys. If there's anyway I can help (non-technical) please let me know 👍👍

Tony Veitia
813-856-6647
________________________________

**Comment by dylee** [comment]
Thank you. I’ve stopped writing software 8 years ago and am rusty, but
would love to help anyway I can. Peace! Dan

**Comment by Jayy001** [comment]
Closing this because we have #385
