### ISSUE TITLE
Feature request: selection eraser with marker plus

### ISSUE THREAD

**Issue by sersorrel** [mb1986/rm-hacks#39]
The marker plus has an eraser on one end, but on stock firmware it's bound to using the regular "white ink" eraser. It would be incredibly useful there was an option to instead have the eraser end of the marker use the selection/lasso eraser, so it could be accessible without opening the sidebar.

see also https://github.com/ddvk/remarkable-hacks/issues/323

**Comment by mb1986** [comment]
I'll check if I can see a possibility to do that. Nonetheless, I'll need your help with testing due to lack of the marker plus pen.

**Comment by PepikVaio** [comment]
I can testing too.

**Comment by mb1986** [comment]
How does it work? You turn around the marker plus and it switches to the eraser right away or when you touch the surface? Could you please add me some longer description? Looking into the code I cannot find anything related...

**Comment by PepikVaio** [comment]
Nothing is switched in the rm panel.
The selected pen or instrument is still lit in the rm panel.

Only the end of the pen erases.

**Comment by mb1986** [comment]
Thanks for the video. I'll dig a little bit more but I think it may not be doable unfortunately.

**Comment by PepikVaio** [comment]
It's okay.
Plus, in the latest update, it no longer uses white ink but actually erases.
