### ISSUE TITLE
Cloud connection issue

### ISSUE THREAD

**Issue by forpascal** [mb1986/rm-hacks#391]
I have version 3.11.2.5 with rM Hacks v0.0.10 and I get the message  "The are some issues with the cloud connection". Anyone else having this issue? Any way so solve it?

**Comment by donut-but-a-brain** [comment]
I believe rM has started not supporting older Xochitl versions for their cloud service, but I may be wrong (they're definitely not supporting it on v3.9.3). I recommend [rcu](http://www.davisr.me/projects/rcu) as a substitute or [remy](https://github.com/bordaigorl/remy/) if you cannot pay for RCU, but in my opinion RCU is well worth it (note that Remy doesn't support v3.x but you can, I believe, still export and then use [rmscene/rmc](https://github.com/ricklupton/rmscene) to convert the .lines to a pdf or something)

**Comment by Eeems** [comment]
You can also use rmfakecloud as a replacement.

That said, you could verify the following before assuming that 3.11.2.5 is no longer supported: https://remarkable.guide/faqs.html#my-device-is-connected-to-wifi-but-can-t-sync-or-check-for-updates-how-can-i-fix-this

According to the tech bulletins, 3.5+ should still work with their cloud: https://support.remarkable.com/s/article/Tech-bulletins

**Comment by mb1986** [comment]
@forpascal, have you had a chance to sort this out? Do you still have the same issue?

**Comment by forpascal** [comment]
> @forpascal, have you had a chance to sort this out? Do you still have the same issue?

Yes, still with the problem. I am exchanging emails with ReMarkable, making some SSH modifications related to the internal clock but so far no luck...

**Comment by Jayy001** [comment]
I don't believe this is an RmHacks related issue.

**Comment by forpascal** [comment]
Never solved. The RM support team dropped me. I am ordering a Boox device to replace the RM2 I cannot use anymore. I am very disappointed.
