### ISSUE TITLE
The .highlights directories dont exist anymore

### ISSUE THREAD

**Issue by hyde-stevenson** [mb1986/rm-hacks#392]
Hello, 

I highlighted many things in my last books, but when I connect to the rm2 there is no `.highlights` directories anymore. I discovered the shell available here :

https://github.com/mb1986/rm-hacks/issues/330

It worked to extract the highlights, and use those directories to get the data. 

Is it linked with the new updates of rmHacks or of the Remarkable OS ? 

Tested with 0.0.10 and 0.0.9 with version 3.11.2.5 and 3.10.2.2063.

**Comment by Jayy001** [comment]
This is a ReMarkable issue, not rmHacks
