### ISSUE TITLE
Add support for 3.7.0.1930

### ISSUE THREAD

**Issue by dstango** [mb1986/rm-hacks#4]
Hi,
thanks for your attempt to revive my Lamy button :-).

Unfortunately rm seems to have released a new Version: https://support.remarkable.com/s/article/Software-release-3-7 -- which appeared on my device today: 3.7.0.1930

I was hoping these patches were a little more version flexible, but that only was a faint dream ;-) ...
Could you adapt the patch accordingly?

Thank you!

**Comment by mb1986** [comment]
Hi @dstango, the patches should be there, could you please confirm they are working correctly on your device? I have rM1 only and it seems to be fine :)

Cheers!

**Comment by dstango** [comment]
@mb1986 thanks for the quick update!
It's working well for me, too! Yet I'm also on rm1, so I don't know about rm2.

Anybody with rm2 here?

**Comment by ard0gg** [comment]
Confirmed patches work for 3.7.0.1930 on my RM2 as well.

**Comment by ard0gg** [comment]
@dstango don't forget to turn off automatic updates.

**Comment by dstango** [comment]
@mb1986 thanks, already did that.
I'll close the issue, hoping rm2 users will be happy or complain if any issues arise.
