### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#40]
Is it possible to support this project so it doesn't end up as a ddvk?

Either financially or with experience?

Please how is it secured when an rm update takes place with upload enhancements?
Won't the rm get destroyed?
Will the enhancements be deleted?

**Comment by mb1986** [comment]
Yes, of course, it is possible to support us. The best way is to show appreciation and provide feedback, as you already do. Thank you for that! I am not considering any financial support at the moment.

Regarding a new version of the rM application, it SHOULD simply remove the hacks on the first run.
