### ISSUE TITLE
Eraser issue

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#41]
I have some issue with eraser (I'm leaving photos). 

![image](https://github.com/mb1986/rm-hacks/assets/36114753/7af6794d-ed37-4e5f-aa4d-c56124dd9e27)

**Comment by mb1986** [comment]
Oh, it is due to more stroke sizes, isn't it?

**Comment by PepikVaio** [comment]
Probably yes.

**Comment by mb1986** [comment]
I assume we do not need additional stroke sizes for eraser at all, correct? If so I will remove them for the eraser tool in the next release.

**Comment by PepikVaio** [comment]
Different widths are good but the last few widths are extreme.

See video.

[(https://1drv.ms/v/s!AhI1pC-JHcQPg_tdQJMPeFIJepVa_A)]

**Comment by mb1986** [comment]
What would you suggest? Removal of the two biggest ones (8 and 13) for the eraser tool?

**Comment by PepikVaio** [comment]
For me yes, it's almost not of use because at least the last one erases half the display.
I don't know who would use it how.

**Comment by mb1986** [comment]
Thanks! I'll remove them then. If anyone finds them useful it'll be possible to add them back.

**Comment by PepikVaio** [comment]
Implement on version 0.0.6

Great work.
