### ISSUE TITLE
Different sensitivity for gestures

### ISSUE THREAD

**Issue by cechurat** [mb1986/rm-hacks#48]
Gestures in the top left corner - swipe down works fine. Swipe-up has a very limited area where to start the swipe (e.g. 35mm from top) and there is not much space left for the swipe. Would it be possible to enlarge this area? Hopefully, it won't make a collision with other gestures.

Swipe down is fine since the important things are just starting point and direction.

(rM1, v0.0.5)

Thank you very much for your work! Looking forward to new features.

Cheers, Tomas

**Comment by mb1986** [comment]
Hi Thomas (@cechurat ), thanks for the feedback! You're not the first one who would like to have a little bit more space for the swipes and there is already an improvement ready for the upcoming v0.0.6.

@PepikVaio, hopefully it'll not break anything at your side.
