### ISSUE TITLE
make the default notebook name be iso formatted datetime

### ISSUE THREAD

**Issue by suppenkaspar109** [mb1986/rm-hacks#5]
If possible, would it be possible to include the "make the default notebook name be iso formatted datetime" ([see #131](https://github.com/ddvk/remarkable-hacks/issues/131))?

**Comment by mb1986** [comment]
Would it be fine if we make it the same as it was: `yyyy-mm-dd_hhmmss`?
The other possibility is to use iso format without timezone as you've requested (`yyy-mm-ddThh:mm:ss`).

**Comment by mb1986** [comment]
Landed with v0.0.2, please confirm that it works as expected :)

**Comment by dreadful-brain** [comment]
perfect! Maybe you should mention in the readme that in order for the correct time to be used in the name, the time zone has to be set accordingly (just like with the DDVK hacks) 
see https://github.com/ddvk/remarkable-hacks#timezones

**Comment by suppenkaspar109** [comment]
Great. Thanks. It works like expected.

**Comment by folofjc** [comment]
This works in 0.0.2. However, is there any way to make this an option? I like the ISO date, but am not a fan of the ISO time as well. I have never needed that (but I acknowledge that some people do), and for me it makes the filenames too long to see what they are.

I am not advocating to remove it, but maybe an option during install.

**Comment by mb1986** [comment]
We are also working on configuration page where one will be able to enable/disable particular hacks :)

Thanks for confirming on notebook name, I'll close this issue and open new ones for:

- configuration switches (inside the app)
- timezone setup (probably from install script)
