### ISSUE TITLE
Pen color and thickness on the pen icon

### ISSUE THREAD

**Issue by ZacharieALES** [mb1986/rm-hacks#50]
Hello,

First, thank you very much for all your work. It is greatly appreciated.

I have a suggestion that I thought I may have read in another post. I mention it regardless since I was not able to find it in the opened issues. Sorry for the potential duplicate.

In ddvk hacks, the pen thickness and color was displayed on the pen icon. I mention it since the next version adds shortcuts to switch the color and thickness. This icon would enable to know which pen you are using without requiring to either display the toolbar or to write with the pen to check (which could then require to erase what you just wrote if it is not the expected pen). It would be useful when you are not sure if you triggered a shortcut or not (I was regularly missing some with ddvk) or if you spent some time reading and are not sure which is the current color/thickness (this happens sometimes to me with the current version).

The fact that with this hack you will just switch between 2 colors and thicknesses instead of the 3 from ddvk makes it a little less essential but still relevant from my point of view.

**Comment by mb1986** [comment]
Hello @ZacharieALES, thank you! Did you have a chance to test a new v0.0.6 which is in pre-release state?
I think it should be already there ;)

```shell
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.6
```

Waiting for your feedback!

**Comment by ZacharieALES** [comment]
Great, I try it right away!

**Comment by ZacharieALES** [comment]
Added in v0.0.6
