### ISSUE TITLE
Settings overflow the display in the landscape mode

### ISSUE THREAD

**Issue by mb1986** [mb1986/rm-hacks#51]

**Comment by rudy0ne** [comment]
Ah, I hadn't considered that it's only with the Type Folio attached, which also shows settings in landscape. See the attached photo:

![Screen Shot 2023-12-05 at 2 16 49 PM](https://github.com/mb1986/rm-hacks/assets/22302732/009d6a45-6310-450b-8c05-e686653fe559)

**Comment by mb1986** [comment]
Ok, I see...
