### ISSUE TITLE
Feature request: Page numbers on the toolbar

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#55]
Please add page numbers in the middle of the toolbar similar to in ddvk-hacks (e.g., 17 of 100).

And thank you for the option to toggle things off, as I’m sure this feature may be distracting to some while very useful to others.

**Comment by mb1986** [comment]
Do you mean displaying page numbers only or any additional functionality?

**Comment by rudy0ne** [comment]
I only meant page numbers, like seen here:

![Screen Shot 2023-12-05 at 4 13 38 PM](https://github.com/mb1986/rm-hacks/assets/22302732/5f3ab604-1822-44b2-81cd-fbe56fbfb4e1)

Unless you had something mind. Perhaps tapping it could bring up the table of contents, or a bookmarks-generated table of contents?

**Comment by PepikVaio** [comment]
Please click to see a list where labels are displayed and click on a label to see pages with labels only.

That would be great.

**Comment by mb1986** [comment]
> Please click to see a list where labels are displayed and click on a label to see pages with labels only.
> 
> That would be great.

I would add that into labels menu, for example long pressing on a label item... but please raise a new issue for that.

**Comment by mb1986** [comment]
> One option on click world be to bring up a small "Go To " window where you could enter a page number, hit Enter / Ok, and jump to that page.

It adds some complexity. Is it really needed when we have the "fast page scroller" at the bottom? Only asking ;)

**Comment by PepikVaio** [comment]
> > One option on click world be to bring up a small "Go To " window where you could enter a page number, hit Enter / Ok, and jump to that page.
> 
> It adds some complexity. Is it really needed when we have the "fast page scroller" at the bottom? Only asking ;)
> 
> 

This function is already in rm.
Just pull it up on the main panel.

I believe it may be useful for someone.

**Comment by Tridens92** [comment]
> > One option on click world be to bring up a small "Go To " window where you could enter a page number, hit Enter / Ok, and jump to that page.
> 
> It adds some complexity. Is it really needed when we have the "fast page scroller" at the bottom? Only asking ;)

That's a fair question!  To me, the "fast page scroller" on the bottom is not very helpful with longer documents.  I frequently use notebooks that have 75, 100+ pages.  With that many pages, the scroller is very finicky.  Tiny movements make large jumps in page changes, etc.

**Comment by atngames** [comment]
Hi, this issue has been solved for a while, let's close it now 😉

**Comment by PepikVaio** [comment]
![image](https://github.com/mb1986/rm-hacks/assets/36114753/aa6bdd49-9772-49a8-bbbd-fa1808c9590c)

For me, it's missing something else like this to make sense.
As I wrote, the function in rm is already there.

**Comment by atngames** [comment]
Ok I'll leave this open, though
