### ISSUE TITLE
Feature request: Battery percentage in document

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#56]
In-document battery percentage would be very helpful. Perhaps just above the clock, or in the middle of the toolbar along with the page number.

Thanks again for the excellent work!

**Comment by mb1986** [comment]
Would you like to see both the battery icon and the percentage or only one of them?

**Comment by mb1986** [comment]
Currently we have the clock and without moving toolbar icons a little bit up there is no space for anything else. Placing battery percentage and/or wifi indicator in the middle of the toolbar will not be so clean in my opinion. Still thinking how to arrange the clock, wifi indicator and battery percentage (with or without the battery level icon).

**Comment by rudy0ne** [comment]
Were you planning to add the battery percentage above the icon that's at the bottom of the page? Because if so, I think if it's small enough a tiny WiFi icon would fit just beside it. It wound't matter if it's not very clear since it would only appear when WiFi is turned on.

**Comment by mb1986** [comment]
Ok, I think I've got it – I've moved the clock to the top and placed the battery level and Wi-Fi indicator at the bottom.
Would that be fine?

**Comment by rudy0ne** [comment]
Sounds brilliant!
