### ISSUE TITLE
Feature Request: Force refresh gesture

### ISSUE THREAD

**Issue by Cindy-Jie-01** [mb1986/rm-hacks#57]

**Comment by mb1986** [comment]
Enabling native experimental gesture — 5-finger tap to refresh.

**Comment by rudy0ne** [comment]
That gesture may be tricky to perform with the same hand you're holding the pen (when the other hand is used to hold or stabilize the device). Would 4-finger tap not register accurately, even if they have to be spread out 15-20mm apart?
