### ISSUE TITLE
Gesture to swap the last two pen thicknesses + eraser: Bug

### ISSUE THREAD

**Issue by digital-tinta** [mb1986/rm-hacks#58]
Version: 0.0.6

I found a bug in the swap pen thickness gesture after using the eraser. Here's the description:

1) Pen thickness 1: write
2) Select thickness 5: write
3)  One finger down: switch to thickness 1, write
4) One finger down: switch to thickness 5, write
5) Press Lamy erase button or manually select eraser with thickness 2 and delete
6) One finger down: switch to thickness 2: NOT 1 as it should

**It seems that it recalls the last thickness of the tool used, not the last thickness of the pen.**

Many thanks for putting up this wonderful project.

**Comment by rudy0ne** [comment]
I think the following, which I wrote in https://github.com/mb1986/rm-hacks/pull/49#issuecomment-1826755661 is related to this:

 _"[1] 
Pen tools, whenever a last used color/stroke gesture is triggered, appear to inherit the color or stroke size of the pen tool that was previously selected if the pen switch was also via gesture. This might work just fine for most pen tools, but results in some weird behavior when it comes to the highlighter: I believe it defaults to yellow highlighter every time when it inherits the previously used pen’s color selection. And the three biggest stroke sizes (5, 8, 13) are probably unusable for a highlighter."_

Currently, a tool will inherit the stroke size and color of the previous tool as its new second option for each attribute.

**Comment by rudy0ne** [comment]
Just to confirm in regards to the pen: If you want to use the pen in blue and red as I do for marking up PDFs, after using the gesture to switch to the highlighter and then back to the pen, the pen’s two colors to switch via the gesture now become either red and black or blue and black, instead of blue and red.
