### ISSUE TITLE
Toggle between fixed set of tools

### ISSUE THREAD

**Issue by jbennett** [mb1986/rm-hacks#59]
Using the side button to toggle the last two tools works great, but I would love the option to toggle between the pen and a single tool, highlighter in my case. 

I typically am in writing mode with the pen/highlighter, switch to the select tool to move stuff around, then go make to writing mode. I don't want the button click to go back to the select tool in that case.

Thanks for your great work so far!

**Comment by atngames** [comment]
I am closing this issue because the quick tools bar seems to fix it.
Hurray
