### ISSUE TITLE
Feature request: Make Lamy tool switch action configurable

### ISSUE THREAD

**Issue by JBlocklove** [mb1986/rm-hacks#66]
I find that the ability to press the button on the Lamy pen to switch tools is a bit annoying, since sometimes it won't register my use of the eraser correctly and I'll end up with the wrong tool after erasing. Can a toggle be added to the settings to turn that functionality off while keeping the eraser working?

Same as this issue, but with these new rm-hacks instead of the ddvk remarkable-hacks: https://github.com/ddvk/remarkable-stylus/issues/8

**Comment by Tanishama** [comment]
> I find that the ability to press the button on the Lamy pen to switch tools is a bit annoying, since sometimes it won't register my use of the eraser correctly and I'll end up with the wrong tool after erasing. Can a toggle be added to the settings to turn that functionality off while keeping the eraser working?
> 
> Same as this issue, but with these new rm-hacks instead of the ddvk remarkable-hacks: [ddvk/remarkable-stylus#8](https://github.com/ddvk/remarkable-stylus/issues/8)

I think that would be a great addition. In my case, as I use my tablet for illustration, I find that, although proper erasing is convenient because It doesn't leave white marks when moving elements around the canvas, sometimes I miss having the brush tool to add white while I hold the pen button instead of the eraser, simply because that tool is more precise, so making find details, like highlights In a character's hair is easier with it.

**Comment by mooomooo** [comment]
If I can extend the feature request some, it may be nice to have separate independent customization options for each of { single click, double click, press-and-hold }; i.e. I would usually like to set single-click -> undo, double click -> tool switch, and press-and-hold -> lasso erase, but I can see others (or myself at some different time) wanting other things.  So perhaps separate option menus could have:

click:
- off
- undo
- tool switch

double click:
- off
- undo
- tool switch

press-and-hold:
- off
- eraser
- lasso erase
- lasso select
- color switch
- highlighter

etc.

**Comment by mooomooo** [comment]
I just got this stylus, which has *both* a side button and the back eraser:
  https://www.amazon.com/King-Write-MR05-Sensitivity-Remarkable/dp/B0CLG96JQ9/

With ddvk's Lamy mod, it's does weird things with the back eraser though -- sometimes it erases as expected, but sometimes it selects the "undo" option that the button is tied to.  I assume a comparable issue may arise here, so maybe I can preempt that by noting what signals get sent for the various clicks / drags?  Is there an `xev` equivalent on the RM2 that I can have running in a terminal while I tap and click and drag?

**Comment by Kelvin88** [comment]
+1 to turning on/off button to switch tool. Drove me crazy today when tool switched when I just want to erase.

**Comment by fcr** [comment]
> +1 to turning on/off button to switch tool. Drove me crazy today when tool switched when I just want to erase.

I agree

**Comment by dstango** [comment]
> I just got this stylus, which has *both* a side button and the back eraser:
>   https://www.amazon.com/King-Write-MR05-Sensitivity-Remarkable/dp/B0CLG96JQ9/

That's a cool pen! Probably @ddvk's Lamy tool doesn't differentiate the two "buttons" (eraser and side button), so it all gets thrown into the same basket. It would be great if that would be possible, and over cloud associate different actions to eraser and side button.

**Comment by mb1986** [comment]
Possibly in the future we'll be able to move this logic out into a separate plugin/library: https://github.com/mb1986/rm-hacks/issues/140.

**Comment by Kelvin88** [comment]
Thank you for introducing option in alpha10 to turn button off/on for tool switch.
