### ISSUE TITLE
New 3.8.3.1976

### ISSUE THREAD

**Issue by imval** [mb1986/rm-hacks#68]
Hi guys, I found this repo through Reddit. But when I looked at the version of my RM2, it asked me to reboot for the auto update. I rebooted and the version is now 3.8.3.1976.

Can I try to install it? It is compatible? Do I risk something?

**Comment by mb1986** [comment]
Is there anyone having 3.8.3.1976 on **rM1**? I think this update happened only for **rM2**...

**Comment by Eeems** [comment]
> Is there anyone having 3.8.3.1976 on **rM1**? I think this update happened only for **rM2**...

It's rM2 only.
