### ISSUE TITLE
Install remarkable-stylus

### ISSUE THREAD

**Issue by Eeems** [mb1986/rm-hacks#7]
It would be a good idea to include installing remarkable-stylus in the installation script to simplify things for users.

You'd just need to create an override file for `xochitl.service` to load the plugin, and pull down the file.

**Comment by mb1986** [comment]
Should be added in 4758acb, please confirm :)

**Comment by Eeems** [comment]
This will not play nice with toltec in the future, as it completely replaces the `xochitl.service` file instead of creating an override. I would recommend updating your install script to do all the steps to install it yourself. This way you can better control what it does.

**Comment by mb1986** [comment]
Good idea, I'll try to make the override instead of replacing the original one.

**Comment by mb1986** [comment]
I think I've done it :) Feedback will be very appreciated ;)
