### ISSUE TITLE
Name of color abbreviated in the top corner

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#71]
It would be great to have an actual indication of the pen/highlighter color next to its corresponding circle when the toolbar’s closed. Or even better, inside the circle if made big enough.

I suggest something like what Boox uses on their devices: BK, GY, WT, BU, RD for the pen. YL, GN, PK, GY for the highlighter.

**Comment by rudy0ne** [comment]
Just an idea: 

![Screen Shot 2023-12-12 at 9 21 02 AM](https://github.com/mb1986/rm-hacks/assets/22302732/fb0bb97b-4064-42b1-8bce-365682323fbe)

**Comment by PepikVaio** [comment]
The first option looks good.

**Comment by mb1986** [comment]
But not all the brush icons have the space in the center of them.

**Comment by PepikVaio** [comment]
True, I wonder what the font inside the circle would look like when the panel is halved?

**Comment by rudy0ne** [comment]
If the circle becomes an issue I think something like this might also work, with the stroke size centered where the period is whenever it’s a single digit:

![3](https://github.com/mb1986/rm-hacks/assets/22302732/ddc6a557-800d-4315-92a3-c8535ef10c6b)

After all, the circle’s only helpful when there’s enough contrast between the last two colors. It’s mostly just there to look pretty until we get a color reMarkable.

**Comment by mb1986** [comment]
I've just added it but I think the text may be to small (?).



I plan to rebuild it for https://github.com/mb1986/rm-hacks/issues/88 by removing this stroke icon for pen thickness and circle for color leaving only digits and textual representation (similarly to what you've suggested).

**Comment by rudy0ne** [comment]
I held the picture next to the pen icon on my rM's screen for reference, and although it is very small I can still distinguish the letters inside the circle. But with a darker circle it probably would've been much harder to see.

**Comment by mb1986** [comment]
I'll leave it as it is for now and I cannot wait for your feedbacks.
For darker backgrounds the text is white ;)
I'm also thinking about some pre-release builds that you'd be able to verify stuff earlier.

**Comment by rudy0ne** [comment]
Awesome, I can't wait! 🔥

**Comment by PepikVaio** [comment]
> I've just added it but I think the text may be to small (?).
> 
> 
> 
> ![IMG20240105122647.jpg](https://github.com/mb1986/rm-hacks/assets/1386931/68eb04be-42c9-48e5-84ed-74ecee014f32)
> 
> 
> 
> I plan to rebuild it for https://github.com/mb1986/rm-hacks/issues/88 by removing this stroke icon for pen thickness and circle for color leaving only digits and textual representation (similarly to what you've suggested).

There doesn't have to be a line for me. Just the thickness number.

**Comment by Kelvin88** [comment]
@mb1986 would you be implementing this for when toolbar’s expanded and clock hidden? Currently need to hide toolbar to see thickness and color selected.

**Comment by rudy0ne** [comment]
Great point! I think it should take the place of the toolbar button somehow. Sorry for my awful photoshop skills:

![Screen Shot 2024-01-09 at 11 13 52 PM](https://github.com/mb1986/rm-hacks/assets/22302732/3de20901-f9fd-46eb-a19f-ce668be1a630)

**Comment by mb1986** [comment]
This one can be tested:

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.3
```

**Comment by PepikVaio** [comment]
When I select some tools, there are annoying touches of the pen icon and text.

One letter would probably be enough:

B = Black
G = Gray
W = White
atc...

**Comment by mb1986** [comment]
And what about **B**lack and **B**lue or **G**reen and **G**ray?

**Comment by PepikVaio** [comment]
You're right, my mistake.

**Comment by PepikVaio** [comment]
I will propose a solution here #8
