### ISSUE TITLE
Display all features in the readme

### ISSUE THREAD

**Issue by ZacharieALES** [mb1986/rm-hacks#73]
The undo/redo gesture does not appear in the readme which made me think that it was not implemented. I started writing an issue about it before realising from [this issue](https://github.com/mb1986/rm-hacks/issues/13) that it was already implemented. By the way, I find your gesture more practical than the one from ddvk hack, thank you very much for that!

It could be interesting to mention this feature and its corresponding shortcut in the readme (and other missing features if any).

**Comment by mb1986** [comment]
The two/three-finger taps are rM native ones. Are you referring to them or something else?

In terms of the feature list, yes - I'm planning to move the release notes into a CHANGELOG.md file (or even leave them only in the Releases section) and have proper features list with descriptions in the main README.md.

**Comment by ZacharieALES** [comment]
Oh I thought it was from you, my bad...
