### ISSUE TITLE
Feature request: In-document button to trigger “light sleep”

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#74]
Light sleep, which can be turned on in the security settings, puts the device to sleep after 20 minutes of inactivity and displays whatever document page was left open. It’s very handy for leaving a to-do list open while conserving battery.

However, there is currently no way to force this since pressing the power button puts it to sleep on the screensaver.

**Comment by PepikVaio** [comment]
I would like the sleep mode to get rid of that big black bar.
Part of the text is not visible and that bothers me.

Would it be possible to put a small icon of a sleeping remarkable somewhere in the corner? :) and this would let the user know that remarkable is sleeping.

**Comment by mb1986** [comment]
Done. Gesture to enable the sleep mode and the possibility to change the text banner into a small icon (⏻) in the corner.

**Comment by PepikVaio** [comment]
I meant some kind of icon where you can see that rm is sleeping :)

I'm posting what I found on the internet:
![suspended_06](https://github.com/mb1986/rm-hacks/assets/36114753/35d99d09-9d97-475d-a01e-7047334bd6fb)

Or what I created myself:
![suspended_01](https://github.com/mb1986/rm-hacks/assets/36114753/4be11540-36c2-452d-b79c-2a52b11eef75)

**Comment by mb1986** [comment]
I am using only available font icons, hence nothing fancy unfortunately. I still think the power icon is the most intuitive one from what I can choose...

**Comment by rudy0ne** [comment]
I can't find any documentation from reMarkable for how long the device would remain in "light sleep" before switching to the screensaver, but I believe it's like 3 hours. Would be great if that could be extended, somewhere around 8 to 12 hours.

**Comment by PepikVaio** [comment]
> Hotovo. Gesto pro aktivaci režimu spánku a možnost změnit textový banner na malou ikonu (⏻) v rohu.

OK, maybe the icon is wrongly displayed in my browser.
What is the unicode character please?

Maybe just a simple "zzz" in the corner would be great.

**Comment by mb1986** [comment]
> I can't find any documentation from reMarkable for how long the device would remain in "light sleep" before switching to the screensaver, but I believe it's like 3 hours. Would be great if that could be extended, somewhere around 8 to 12 hours.

I think it may be doable but if you really need it please create a separate issue.

**Comment by rudy0ne** [comment]
Will do, thanks!


And here are my lockscreen icon suggestions if they’re available:
- Small padlock. 
- A tiny coffee cup! The implication being that the reMarkable will need coffee once it wakes up : )

**Comment by mb1986** [comment]
Currently I've added `...zzZ` text in the top right corner while sleeping.
Nonetheless, from the icons you've suggested there is only a padlock as far as I can see.
