### ISSUE TITLE
Extend the duration of "light sleep" mode

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#76]
From the company’s website: _“Your reMarkable will go into sleep after **2 hours and 40 minutes** in light sleep or after 3 hours of inactivity.”_

Please extend light sleep beyond those 2 hours and 40 mins. Ideally to 12 hours, or user-configurable to choices like 8 hours, 24 hours, and until the device is powered off.

**Comment by Jayy001** [comment]
I'm going to merge this into #160
