### ISSUE TITLE
Toolbar page numbers are misaligned when in left-handed mode

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#84]
In left-handed mode, the toolbar page numbers implemented in #77 are displayed as follows: The top number is aligned right instead of left, and the bottom number is aligned left instead of right. I feel they should be aligned the same as they are in right-handed mode.

**Comment by Tridens92** [comment]
I'm also a left-hander, and not sure this is related or the same request.

Currently the numbers read right-to-left, rather than left-to-right.  For example, right now it reads 34 /30, rather than 30/34 (page 30 of 34).  Could this be swapped?

**Comment by mb1986** [comment]
I think it is the same issue. I'll fix it in the next release.
