### ISSUE TITLE
Feature Request: Better content button integration

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#85]
Please edit the content button so that it is a separate function, not just a function pulled from another function.

As soon as I open the site overview - the site overview opens - OK
As soon as I open the table of contents - the table of contents opens - OK
When I open the table of contents and select a page and then press the page overview, the table of contents opens :(

I understand why this is happening but it is very confusing.
Can it be modified so that every time I click on the table of contents it opens the table of contents and when I click on the page overview it always opens the page overview?

The second problem, as soon as I open the overview of the pages, I have a back button, I get to the document.
Once I open the table of contents, I also have the back but I get to the page table of contents.
So I have to double tap to get to the document.

- [ ] Modify the buttons to open the correct screen every time
- [ ] Adjust the back button so I can get to the document with one press.

**Comment by PepikVaio** [comment]
https://1drv.ms/v/s!AhI1pC-JHcQPg_w-8GoKxVifd1UjQQ
https://1drv.ms/v/s!AhI1pC-JHcQPg_w98GoKxVifd1UjQQ

**Comment by mb1986** [comment]
Thanks for the videos!
