### ISSUE TITLE
Increase area to trigger “light sleep” gesture

### ISSUE THREAD

**Issue by rudy0ne** [mb1986/rm-hacks#87]
The area to trigger the “light sleep” gesture implemented in #77 could be a little bigger. Looks like we currently have about 15 mm from the top edge of the screen, but it might be best if it’s like 25 or 30 mm for better accuracy.

**Comment by PepikVaio** [comment]
I have no problem using the gesture.
It works reliably for me - but we can increase the area, it will probably be beneficial.

I'm having trouble getting used to it - I write on the display and nothing happens :) until I notice "...zzZ" :)
