### ISSUE TITLE
Additional table-of-contents toolbar button

### ISSUE THREAD

**Issue by zelomel** [mb1986/rm-hacks#91]
Hi,
Maybe I didn't understand what this is for, but where is this new button?

By the way, thank you very much for your work. I was stuck in 2.15 version until you revived the ddvk-hack.

Laurent

**Comment by mb1986** [comment]
Hi Laurent, the additional button shows up on the toolbar when your notebook/pdf contains a table of contents.

![IMG20231213093746~2.jpg](https://github.com/mb1986/rm-hacks/assets/1386931/e57769cd-ae8d-4270-8da9-ceccb88e0df3)

Cheers!

**Comment by zelomel** [comment]
OK, I was trying with pdf files that I thought contained a table of contents but they don't.
With another pdf file, everything is fine.

Thanks

**Comment by mb1986** [comment]
Cool, thanks, closing this issue.
