### ISSUE TITLE
Feature request: Fake keyboard connection in order to get the whole interface in landscape mode

### ISSUE THREAD

**Issue by pragmatically-dev** [mb1986/rm-hacks#95]
I was taking a look over cache qmlc file with hex editor and I found this:
SavedDeviceInfo.keyboardConnected&window{DeviceInfo.keyboardConnected 

and i was wondering if there is a way to fake that connection

**Comment by mb1986** [comment]
Yes, we can simulate the orientation based on the `keyboardConnected` value. I am just considering where to place the toggle for switching the orientation, as it affects the orientation of all views.

**Comment by PepikVaio** [comment]
Can it be in more than one place?
In the workbook under the sharing icon - when you put the settings there - although I still think it deserves its own icon :)

And then on the main screen next to "Sort by".
There's a bar there that's not occupied.

**Comment by mb1986** [comment]
I've just tested it and I am able to set any orientation you may want (four in total).

**Comment by PepikVaio** [comment]
> I've just tested it and I am able to set any orientation you may want (four in total).
>
That's fine - if I understand correctly.
Because when the keyboard is plugged in, the bottom edge is on the right.

If I was typing on a reMarkable without a keyboard I wanted landscape, the bottom edge on the left would be better for me.

**Comment by mb1986** [comment]
You will be able to choose one orientation from:

- Landscape orientation, display width is greater than display height.
- Portrait orientation, display height is greater than display width, rotated 90 degree clockwise relative to landscape.
- Inverted landscape orientation, rotated 180 degrees relative to landscape.
- Inverted portrait orientation, rotated 180 degrees relative to portrait.

See: https://doc.qt.io/qt-6.5/qt.html#ScreenOrientation-enum

**Comment by dreadful-brain** [comment]
The "Inverted portrait orientation, rotated 180 degrees relative to portrait." will be very handy, if remarkable needs a charge while you still want to use it. My usb cable comes from the rear of my desk and with that new feature I do not have to circle it around the device anymore, I could just turn remarkable upside down.
Michal you're awesome!

**Comment by PepikVaio** [comment]
> "Orientace na výšku, otočená o 180 stupňů vzhledem k portrétu." bude velmi užitečný, pokud pozoruhodný potřebuje nabití, když jej stále chcete používat. Můj usb kabel vychází ze zadní části mého stolu a díky této nové funkci už s ním nemusím kroužit kolem zařízení, mohl bych se jen pozoruhodně obrátit vzhůru nohama. Michale jsi super!

It is true :)

**Comment by PepikVaio** [comment]
Here's what it looks like when there are lots of subfolders (reMarkable did well).
So a drop down menu would still fit :)

![IMG_3202](https://github.com/mb1986/rm-hacks/assets/36114753/82df3213-7af5-459d-9990-6b94775d69b7)

**Comment by mb1986** [comment]
Frankly speaking, I am considering adding a small icon on the right-hand side of this 'Alphabetical' dropdown. It would toggle between different orientations, such as portrait, landscape, portrait 180, landscape 180, and then back to portrait, and so on. Do we really need a dropdown for that?

**Comment by PepikVaio** [comment]
Yeah, good idea.
It can cycle.

**Comment by mb1986** [comment]
Implemented, waiting for the release.

![IMG20240103235804~2.jpg](https://github.com/mb1986/rm-hacks/assets/1386931/d90b7fdd-a1e0-4f81-9763-b9a87d3b8232)

**Comment by PepikVaio** [comment]
I just tried it and I think it's impractical. If I want to get to the last turn, I have to "chase" the button all over the place.
Maybe it would be worth making a drop down menu?

So far the option is not in the share button - will it be there?

Thank you.

**Comment by PepikVaio** [comment]
One more mistake (maybe)?
As soon as I rotate the screen, the sleep screen rotates as well.
But I already had the sleep screen in landscape and now it's flipped to portrait, so I can see half of it.

**Comment by mb1986** [comment]
1. Would it help to add long press for coming back to the native portrait orientation?
2. Do we really need it in Share foldout?
3. This is how it works, it rotates the whole screen including sleep screen ;)

**Comment by PepikVaio** [comment]
1. would be greate.
But for my orientation I have to press 3 times, it's not that I have to press 3 times but that I have to look for the button 3 times (each time in a different place) - Let's wait for others to try and write their feelings.

2. Uh, it might come in handy.
Ideally do what should be displayed in the menu (separate settings?). Maybe someone doesn't want all the switches?


3. I don't find it neat - can't it be separated?
**Can someone please test how it is with the original keyboard???
How does the sleep screen appear when the keyboard is connected.**

**Comment by rudy0ne** [comment]
>    **Can someone please test how it is with the original keyboard???
>    How does the sleep screen appear when the keyboard is connected.**

The screen orientation button flips with the Type Folio connected, but it takes effect only once you disconnect it.

https://github.com/mb1986/rm-hacks/assets/22302732/adfc970f-770d-4765-9c13-2e5545ded018


And the sleep screen is in landscape with the Type Folio connected.

**Comment by PepikVaio** [comment]
Please, connect to keyboard and go to sleepscreen.
And take photo.

**Comment by rudy0ne** [comment]
![Screen Shot 2024-01-09 at 3 41 03 PM](https://github.com/mb1986/rm-hacks/assets/22302732/32d69e9c-65dc-4bfc-a0e3-1539a22a3b4a)

**Comment by PepikVaio** [comment]
Of course, it's clear to me now.
reMarkable has this simple sleep screen and doesn't mind turning over.

I have a picture and then it looks like this:

Original:
![IMG_3230](https://github.com/mb1986/rm-hacks/assets/36114753/b6098474-34f8-4135-b7ee-b9fbb024f5ad)


Then:
![IMG_3231](https://github.com/mb1986/rm-hacks/assets/36114753/ed2b430f-cc28-4fe1-9ee5-411cb01909a3)

**Comment by mb1986** [comment]
> The screen orientation button flips with the Type Folio connected, but it takes effect only once you disconnect it.

Is it expected behavior? My thinking was: whatever orientation you have, when connected to the Type Folio the orientation should change like without the hacks.

**Comment by rudy0ne** [comment]
> > The screen orientation button flips with the Type Folio connected, but it takes effect only once you disconnect it.
>
> Is it expected behavior? My thinking was: whatever orientation you have, when connected to the Type Folio the orientation should change like without the hacks.

I'm not sure I know what you mean. But I made a short video to make sure that how I described it is clear. Also, I wasn't actually wishing for the Type Folio to work in portrait. Although it would be a little amusing to see.

https://github.com/mb1986/rm-hacks/assets/22302732/21de3350-d2e3-44c5-b85d-00c522d8a890

**Comment by PepikVaio** [comment]
I think it's okay.
No need to rotate when the keyboard is attached.

But maybe remove the icon or add transparency?

**Comment by rudy0ne** [comment]
> I think it's okay. No need to rotate when the keyboard is attached.
Only if a pogo pin adapter base existed, then you could rotate the tablet and attach the Type Folio in portrait mode.

> But maybe remove the icon or add transparency?

Or just lock the button. But I don't think anyone will be accidentally tapping it with the Type Folio connected. The button is very small, after all.

**Comment by PepikVaio** [comment]
> > I think it's okay. No need to rotate when the keyboard is attached.
> > Only if a pogo pin adapter base existed, then you could rotate the tablet and attach the Type Folio in portrait mode.
> 
> > But maybe remove the icon or add transparency?
> 
> Or just lock the button. But I don't think anyone will be accidentally tapping it with the Type Folio connected. The button is very small, after all.

The button is small, that's true but it's a good habit when something shouldn't work to let the user know it shouldn't work.

**Comment by rudy0ne** [comment]
Good point. Or that it shouldn't work...just yet 😆

**Comment by rudy0ne** [comment]
> I just tried it and I think it's impractical. If I want to get to the last turn, I have to "chase" the button all over the place. Maybe it would be worth making a drop down menu?

The rotation menu in Boox always looked confusing to me.

![Screen Shot 2024-01-09 at 6 26 06 PM](https://github.com/mb1986/rm-hacks/assets/22302732/7aef17c3-01a9-4224-a93f-f33b5fb81068)

I vote for an option in rm-hacks settings to choose whether the button will rotate the display clockwise or counter-clockwise.

**Comment by dreadful-brain** [comment]
> Of course, it's clear to me now. reMarkable has this simple sleep screen and doesn't mind turning over.
 
I have the same experience with my sleepscreen.
What about checking whether there are 2 sleepscreens (suspended_ls.png and suspended_p.png)?
And if this is the case, then simply rename the files when rotating, for example, so that the correct one is always called sleepscreen.png. But perhaps you can also simply set a property to the correct file name.

**Comment by PepikVaio** [comment]
I don't think there are two pictures.

**Comment by dreadful-brain** [comment]
> I don't think there are two pictures.

I'm sorry, I didn't make myself clear. I am thinking of the following use cases:

1. If someone just wants one sleep screen for all screen orientations, then everything stays the same, he uploads one "suspended.png" with resolution 1404×1872.

2. If someone (like you and me) wants separate sleepscreens for landscape and portrait orientation, he creates and uploads 2 separate files:

- suspended_p.png with the resolution 1404x1872 for portrait view.
- suspended_ls.png with the resolution 1872x1404 for landscape view.

The hacks could then simply copy the suspended_ls.png over the suspended.png when switching from portrait to landscape. And when switching back to portrait, copy the suspended_p.png to the suspended.png

**Comment by PepikVaio** [comment]
OK, good idea.
