### ISSUE TITLE
Bug: Icon pen number and color

### ISSUE THREAD

**Issue by digital-tinta** [mb1986/rm-hacks#97]
Bug behavior:

1. Create a new notebook  (but same behavior in an old one)
2. Swipe down one finger to close toolbar; only top left icon.
3. Write with default pen (fineliner), thickness 2, color black; icon correct
4. Swipe down top right to change to thickness 3; icon correct
5. Swipe down top right to change to thickness 2; icon correct
6. Swipe down **top left** to switch between the last two tools, and icon shows only pen (fineliner). 
            Note, I had not used other tool, so it changes between thicknesses with the same writing tool
7. Swipe down top left, changes "tool"; icon shows correct thickness and color
8. Swipe down top left, changes "tool"; icon incorrect, only pen
9. All subsequent swipes down repeat behavior in 7. and 8.
            Note: .7. and 8. change thickness as expected.

Again, many thanks for this wonderful project.

**Comment by atngames** [comment]
Do you still have this bug ?

The hacks have gone a long way since you created this issue ;)

**Comment by digital-tinta** [comment]
Issue solved in new versions.
