### ISSUE TITLE
Feature Request: Ability to Disable Notebook Scroll

### ISSUE THREAD

**Issue by begtognen** [mb1986/rm-hacks#98]
As I'm always inadvertently scrolling down on the notebook page, it would be great to have the option to disable the scroll entirely.

**Comment by PepikVaio** [comment]
The same like #47.

**Comment by begtognen** [comment]
Whoops - my apologies, I didn't mean to duplicate an already existing thread. Thanks so much for your awesome hacks and all the work you've put into them.

**Comment by PepikVaio** [comment]
It is not my work :)
